SDGVM Update Project: light_methods Module Reference
light_methods Module Reference
Functions/Subroutines
real(dp) function dayl (lat, day)
Calculates daylength (h) for the gridcell lat and day of year.
subroutine pfd (lat, day, hrs, cloud, direct, diffuse, total)
Calculates total,direct and diffuse radiation for the day.
subroutine pfd_ant (lat, day, hrs, cloud, direct, diffuse, total, swr, read_par, subd_par, t, total_t, calc_zen, cos_zen)
Calculates total,direct and diffuse radiation for the day.
real(dp) function pfd_without_cloud (lat, day, hrs)
Photon Flux Density.
real(dp) function pfd2 (lat, day, hrs)
Photon Flux Density.
real(dp) function pfds (tdss, hrs)
Photon Flux Density.
Function/Subroutine Documentation
dayl()
real(dp) function light_methods::dayl (real(dp) lat, integer day)
Calculates daylength (h) for the gridcell lat and day of year.
Author
Mark Lomas
Date
Feb 2006
Definition at line 21 of file light_methods.f90.
Referenced by phenology_methods::phenology3(), sdgvm(), and crops::seasonality().
pfd()
subroutine light_methods::pfd (real(dp) lat, integer day, real(dp) hrs, real(dp) cloud, real(dp) direct, real(dp) diffuse, real(dp) total)
Calculates total,direct and diffuse radiation for the day.
Units oof outputs are mol/m2/sec Needs interpolated daily values of cloud cover instead of the same one for all the days in the month
Author
Mark Lomas
Date
Feb 2006
Parameters
hrs day length in hours
total Average direct and diffuse radiation in mole/m2/sec
direct Average direct radiation in mole/m2/sec
diffuse Average diffuse radiation in mole/m2/sec
Definition at line 65 of file light_methods.f90.
Referenced by crops::seasonality().
pfd2()
real(dp) function light_methods::pfd2 (real(dp) lat, integer day, real(dp) hrs)
Photon Flux Density.
Author
Mark Lomas
Date
Feb 2006
Definition at line 368 of file light_methods.f90.
pfd_ant()
subroutine light_methods::pfd_ant (real(dp) lat, integer day, real(dp) hrs, real(dp) cloud, real(dp) direct, real(dp) diffuse, real(dp) total, real(dp) swr, logical read_par, logical subd_par, integer t, integer total_t, logical calc_zen, real(dp) cos_zen)
Calculates total,direct and diffuse radiation for the day.
Units oof outputs are mol/m2/sec Needs interpolated daily values of cloud cover instead of the same one for all the days in the month
Author
Mark Lomas
Date
Feb 2006
Definition at line 166 of file light_methods.f90.
Referenced by productivity_methods::nppcalc(), and sdgvm().
pfd_without_cloud()
real(dp) function light_methods::pfd_without_cloud (real(dp) lat, integer day, real(dp) hrs)
Photon Flux Density.
Author
Mark Lomas
Date
Feb 2006
Definition at line 318 of file light_methods.f90.
pfds()
real(dp) function light_methods::pfds (real(dp) tdss, real(dp) hrs)
Photon Flux Density.
From Total Downward Shortwave at the Surface (TDSS) - for use with GCM data.
Author
Mark Lomas
Date
Feb 2006
Definition at line 417 of file light_methods.f90.