SDGVM Update Project: system_state Module Reference
system_state Module Reference
Data Types
type systemstate
Variables
type(systemstate), dimension(max_cohorts), public ssv
type(systemstate), public ssv_temp
Variable Documentation
ssv
type(systemstate), dimension(max_cohorts), public system_state::ssv
Definition at line 137 of file system_state.f90.
Referenced by state_methods::accumulate_burnt_soil_res(), state_methods::accumulate_dist_soil_res(), veg_dynamics::addbio(), phenology_methods::allocation(), productivity_luna_methods::assj3(), productivity_luna_methods::assj4(), productivity_luna_methods::assvmax3(), veg_dynamics::barerec(), state_methods::combine_cohorts(), state_methods::compress_state(), veg_dynamics::cover(), crops::crop_outputs(), doly::dolyday(), doly::evapotranspiration(), state_methods::ft_cover(), veg_dynamics::growth(), crops::harv(), hydrology_methods::hydrology(), veg_dynamics::initialise_new_cohorts(), state_methods::initialise_state(), state_methods::initialise_state_cohort(), crops::irrigate(), phenology_methods::lai_add(), phenology_methods::lai_dist(), state_methods::make_co2ftmap(), veg_dynamics::mklit(), veg_dynamics::newgrowth(), phenology_methods::phenology1(), phenology_methods::phenology2(), phenology_methods::phenology3(), state_methods::remove_cohort(), state_methods::restrict_cohort_numbers(), phenology_methods::root_add(), phenology_methods::root_dist(), sdgvm(), state_methods::set_misc_values(), state_methods::set_new_soil_res(), state_methods::set_new_soil_res2(), phenology_methods::stem_add(), phenology_methods::stem_dist(), state_methods::sum_carbon(), phenology_methods::suma_add(), and veg_dynamics::thin().
ssv_temp
type(systemstate), public system_state::ssv_temp
Definition at line 137 of file system_state.f90.
Referenced by state_methods::combine_cohorts().