SDGVM Update Project: file_object Module Reference
file_object Module Reference
Variables
type(noids) fun
type(noids) funmisc
Variable Documentation
fun
type(noids) file_object::fun
Definition at line 347 of file file_io_methods.f90.
Referenced by veg_dynamics::grassrec(), state_methods::initialise_state(), sdgvm1::land_site_check(), soil_methods::ndyn(), open_files::open_default(), open_files::open_diag(), open_files::open_optional(), open_files::open_site_info(), open_files::open_state(), open_files::open_tile_pft(), sdgvm(), and open_files::write_lat_lon().
funmisc
type(noids) file_object::funmisc
Definition at line 347 of file file_io_methods.f90.