SDGVM Update Project: veg_dynamics Module Reference
veg_dynamics Module Reference
Functions/Subroutines
subroutine cover (nft, tmp, prc, firec, fireres, fprob, ftprop, check_closure)
cover
subroutine initialise_new_cohorts (nft, ftprop, check_closure)
INITIALISE_NEW_COHORTS.
subroutine growth (nft, lai, stembio, rootbio, check_closure)
subroutine thin (nft, npp, lai, nps, evp, slc, check_closure)
real(dp) function find (tmp, prc)
subroutine c3c42 (ftprop, npp, range)
subroutine c3c4 (ftprop, c3old, c4old, npp, nps)
subroutine grassrec (nft, ftprop, gold, x, nat_map)
subroutine barerec (ftprop, bpaold, x)
subroutine addbio (npp, nps, npr)
subroutine mklit (ftmat, slc, rlc, sln, rln, npp, nps, npr)
real(dp) function stlit (age, mat)
subroutine vegmat (nft, ftmor, ftwd, ftxyl, ftpd, evp, lai, npp, nps, ftmat)
subroutine fire (dprc, dtmp, fri, fprob)
subroutine newgrowth (fprob, npp, nps, fireres, firec)
NEWGROWTH.
Function/Subroutine Documentation
addbio()
subroutine veg_dynamics::addbio (real(dp), dimension(max_cohorts) npp, real(dp), dimension(max_cohorts) nps, real(dp), dimension(max_cohorts) npr)
Definition at line 924 of file veg_dynamics.f90.
References site_parameters::ssp, and system_state::ssv.
barerec()
subroutine veg_dynamics::barerec (real(dp), dimension(max_cohorts) ftprop, real(dp) bpaold, real(dp) x)
Definition at line 893 of file veg_dynamics.f90.
References site_parameters::ssp, and system_state::ssv.
c3c4()
subroutine veg_dynamics::c3c4 (real(dp), dimension(max_cohorts) ftprop, real(dp) c3old, real(dp) c4old, real(dp), dimension(max_cohorts) npp, real(dp), dimension(max_cohorts) nps)
Definition at line 804 of file veg_dynamics.f90.
c3c42()
subroutine veg_dynamics::c3c42 (real(dp), dimension(max_cohorts) ftprop, real(dp), dimension(max_cohorts) npp, real(dp) range)
Definition at line 780 of file veg_dynamics.f90.
cover()
subroutine veg_dynamics::cover (integer nft, real(dp), dimension(12,31) tmp, real(dp), dimension(12,31) prc, real(dp) firec, integer fireres, real(dp) fprob, real(dp), dimension(max_cohorts) ftprop, logical check_closure)
cover
! First it calculates empirical fire probability by calling FIRE subroutine. NEWGROWTH will kill cohorts that exceeded the permissible age
for the ft and do similar for cohorts with low NPP and fire.It will also set ssvcover to zero for those cases which means cover will be available for use.It then proportianally assigns new cover to the fts that
need to make the biggest jump in cover from the previous year to the
current.ftprop(ft) now describes the new cover to be assigned to each ft.
Author
Mark Lomas
Date
Feb 2006
Definition at line 40 of file veg_dynamics.f90.
References fire(), newgrowth(), site_parameters::ssp, system_state::ssv, and state_methods::sum_carbon().
find()
real(dp) function veg_dynamics::find (real(dp), dimension(12) tmp, real(dp), dimension(12) prc)
Definition at line 745 of file veg_dynamics.f90.
fire()
subroutine veg_dynamics::fire (real(dp), dimension(12,31) dprc, real(dp), dimension(12,31) dtmp, real(dp) fri, real(dp) fprob)
Definition at line 1063 of file veg_dynamics.f90.
References func::minx(), and tuning_parameters::tgp.
Referenced by cover().
grassrec()
subroutine veg_dynamics::grassrec (integer nft, real(dp), dimension(max_cohorts) ftprop, real(dp) gold, real(dp) x, integer, dimension(8) nat_map)
Definition at line 853 of file veg_dynamics.f90.
References file_object::fun, and site_parameters::ssp.
growth()
subroutine veg_dynamics::growth (integer nft, real(dp), dimension(max_cohorts) lai, real(dp) stembio, real(dp) rootbio, logical check_closure)
Definition at line 385 of file veg_dynamics.f90.
References site_parameters::ssp, system_state::ssv, state_methods::sum_carbon(), and thin().
initialise_new_cohorts()
subroutine veg_dynamics::initialise_new_cohorts (integer nft, real(dp), dimension(max_cohorts) ftprop, logical check_closure)
INITIALISE_NEW_COHORTS.
! It gets ftprop(ft) which holds the cov it needs to add for each ft for this year from the COVER subroutine.One new cohort for each ft will carry this cover.It will be initialised relatively to its cover and depending on what was left in the pools from cohorts that died.
Author
Mark Lomas
Date
Feb 2006
Definition at line 136 of file veg_dynamics.f90.
References state_methods::initialise_state_cohort(), state_methods::reset_soil_res(), state_methods::set_new_soil_res(), site_parameters::ssp, system_state::ssv, and state_methods::sum_carbon().
mklit()
subroutine veg_dynamics::mklit (real(dp), dimension(max_cohorts) ftmat, real(dp), dimension(max_cohorts) slc, real(dp), dimension(max_cohorts) rlc, real(dp), dimension(max_cohorts) sln, real(dp), dimension(max_cohorts) rln, real(dp), dimension(max_cohorts) npp, real(dp), dimension(max_cohorts) nps, real(dp), dimension(max_cohorts) npr)
Definition at line 949 of file veg_dynamics.f90.
References site_parameters::ssp, system_state::ssv, and stlit().
newgrowth()
subroutine veg_dynamics::newgrowth (real(dp) fprob, real(dp), dimension(max_cohorts) npp, real(dp), dimension(max_cohorts) nps, integer fireres, real(dp) firec)
NEWGROWTH.
! Compute newgrowth and alter cover array accordingly.
It first checks the age of each cohort.If it has exceeded the limit set by pftmort,it kills it by calling the ACCUMUATE_DIST_SOIL_RES. It then adds +1 to the age of all other cohorts.Calls COMPRESS_STATE to remove dead/empty cohorts resulting from the previous step. Performs similar process to kill cohorts due to low NPP and fire.
Author
Mark Lomas
Date
Feb 2006
Definition at line 1159 of file veg_dynamics.f90.
References state_methods::accumulate_burnt_soil_res(), state_methods::accumulate_dist_soil_res(), state_methods::compress_state(), dims::max_pfts, site_parameters::ssp, and system_state::ssv.
Referenced by cover().
stlit()
real(dp) function veg_dynamics::stlit (real(dp) age, real(dp) mat)
Definition at line 981 of file veg_dynamics.f90.
Referenced by mklit(), and thin().
thin()
subroutine veg_dynamics::thin (integer nft, real(dp), dimension(max_cohorts) npp, real(dp), dimension(max_cohorts) lai, real(dp), dimension(max_cohorts) nps, real(dp), dimension(max_cohorts) evp, real(dp), dimension(max_cohorts) slc, logical check_closure)
Definition at line 462 of file veg_dynamics.f90.
References site_parameters::ssp, system_state::ssv, stlit(), and state_methods::sum_carbon().
Referenced by growth().
vegmat()
subroutine veg_dynamics::vegmat (integer nft, integer, dimension(max_cohorts) ftmor, real(dp), dimension(max_cohorts) ftwd, real(dp), dimension(max_cohorts) ftxyl, real(dp), dimension(max_cohorts) ftpd, real(dp), dimension(max_cohorts) evp, real(dp), dimension(max_cohorts) lai, real(dp), dimension(max_cohorts) npp, real(dp), dimension(max_cohorts) nps, real(dp), dimension(max_cohorts) ftmat)
Definition at line 1014 of file veg_dynamics.f90.