SDGVM Update Project: metdos Module Reference
metdos Module Reference
Functions/Subroutines
real(dp) function declination_fn (DAY_OF_YEAR, DAYS_IN_YEAR, PI)
real(dp) function radian_to_degree_fn ()
real(dp) function degree_to_radian_fn ()
real(dp) function pivalue_fn ()
real(dp) function daylength_fn (LATITUDE_RAD, DECLINATION, PI)
real(dp) function dawn_fn (DAYLENGTH)
real(dp) function dusk_fn (DAYLENGTH)
integer function day_of_year_fn (DD, MM, DAYSINYEAR)
integer function days_in_year_fn (YYYY)
real(dp) function declination2_fn (DAY_OF_YEAR)
real(dp) function daylength2_fn (LATITUDE_RAD, DAY_OF_YEAR, PI)
real(dp) function dawn_hourangle_fn (DECLINATION, LATITUDE_RAD)
real(dp) function rad_et_day2_fn (LATITUDE_RAD, DECLINATION, DAWN_HOURANGLE, SOL_ELLIPSE, SOL_CONST, PI)
real(dp) function rad_et_day_fn (LATITUDE_RAD, DECLINATION, DAYLENGTH, SOL_ELLIPSE, SOL_CONST, PI)
real(dp) function rad_et_day3_fn (LATITUDE_RAD, DECLINATION, SOL_ELLIPSE, DAWN, DUSK, SOL_CONST, PI)
real(dp) function vp_sat_fn (TEMP_C)
real(dp) function sol_elev_fn (LATITUDE_RAD, DECLINATION, SOLAR_TIME, PI)
real(dp) function azimuth_fn (LATITUDE_RAD, DECLINATION, SOL_ELEV)
real(dp) function rad_terra_day_fn (RAD_ET_DAY, LATITUDE_RAD, CLOUD_COVER, BETA)
real(dp) function diffprop_day_fn (TRANS_PROP_DAY)
real(dp) function solar_ellipse_fn (DAY_OF_YEAR, DAYS_IN_YEAR, PI)
real(dp) function solar_ellipse2_fn (DAY_OF_YEAR)
real(dp) function solar_time_fn (GMT, LONGITUDE_RAD, DAY_OF_YEAR, PI)
real(dp) function gmt_fn (SOLAR_TIME, LONGITUDE_RAD, DAY_OF_YEAR, PI)
real(dp) function temp_hour_fn (HOUR, TEMPMAX, TEMPMIN, PI)
real(dp) function humidity_inst_fn (VP_UNSAT_BASE, VP_SAT_NOW)
subroutine rain_day_sub (NO_RAIN_DAYS, RAIN_IN_MONTH, DAYS_IN_MONTH, SEED1, SEED2, SEED3, RAIN)
subroutine rain_duration_sub (RAIN, RAIN_DURATION, RAIN_INTENSITY, DAYS_IN_MONTH)
real(dp) function rndf (XLO, XHI, J1, J2, J3)
real(dp) function trans_prop_day_fn (RAD_ET_DAY, RAD_TERRA_SW_DAY)
real(dp) function angstrom_beta_fn (LATITUDE_RAD)
real(dp) function diffprop_day2_fn (TRANS_PROP_DAY, BETA)
real(dp) function rad_terra_inst_fn (DAWN, DUSK, DAYLENGTH, HOUR, RAD_TERRA_DAY, PI)
real(dp) function windspeed_inst_fn (WIND_RUN_DAY, HOUR)
real(dp) function rad_terra_sunday_fn (DAYLENGTH, SUN_HOURS, RAD_ET_DAY)
real(dp) function temp_air_amplitude_fn (TRANS_PROP_DAY, A_SKY, ANGSTROM_BETA, C_SKY)
real(dp) function diff_prop_hour_fn (DIFF_PROP_DAY, SOL_ELEV)
real(dp) function temp_max_day_fn (TEMP_AIR_AMPLITUDE, TEMP_DAY_MEAN)
real(dp) function temp_min_day_fn (TEMP_AIR_AMPLITUDE, TEMP_DAY_MEAN)
real(dp) function temp_air_amplitude2_fn (TEMP_MAX_DAY, TEMP_MIN_DAY)
real(dp) function temp_day_mean_fn (TEMP_MAX_DAY, TEMP_MIN_DAY)
real(dp) function temp_day_mean2_fn (TEMP_MEAN_MONTH, TEMP_SD_MONTH, TEMP_AUTOCORR_MONTH, TEMP_YESTERDAY, IS1, IS2, IS3, NORMSWITCH)
real(dp) function wind_day_mean_fn (WIND_MONTH_MEAN, WIND_SD_MONTH, WIND_AUTOCORR_MONTH, WIND_YESTERDAY, IS1, IS2, IS3, NORMSWITCH)
integer function days_in_month_fn (MM, DAYSINYEAR)
real(dp) function radian_from_degree_fn (DEGREES, PI)
subroutine northeast_to_latlong_sub (EASTING, NORTHING, LATITUDE, LONGITUDE, PI)
real(dp) function daydata_from_monthdata_fn (MONTHDATA, DAY_OF_MONTH)
real(dp) function humidity_fn (TEMP_AIR_AMPLITUDE)
subroutine get_gridsq_sub (GRIDSIZE, LATITUDE, LONGITUDE, GRIDLAT, GRIDLONG, PI, LONG_OFFSET)
real(dp) function vp_unsat2_fn (VP_SAT, HUMIDITY)
real(dp) function rad_to_radpar_fn (RAD, RAD_PERC_PAR)
real(dp) function radpar_to_rad_fn (RADPAR, RAD_PERC_PAR)
real(dp) function radpar_to_radppfd_fn (RADPAR, PPFDCONV)
real(dp) function radppfd_to_radpar_fn (RADPPFD, PPFDCONV)
real(dp) function rad_diff_above_fn (DIFFPROP_DAY, RAD_TERRA_DAY, ALBEDO_DIFF)
real(dp) function rad_beam_above_fn (DIFFPROP_DAY, RAD_TERRA_DAY, ALBEDO_BEAM)
subroutine rain_duration2_sub (RAIN, RAIN_DURATION, RAIN_INTENSITY, DAYS_IN_MONTH, IS1, IS2, IS3)
real(dp) function vp_sat2_fn (TEMP_C)
real(dp) function trans_prop_day2_fn (TEMP_AIR_AMPLITUDE, A_SKY, ANGSTROM_BETA, C_SKY)
real(dp) function gammadist_fn (A, B, C, SEED1, SEED2, SEED3)
real(dp) function norm_from_rand_fn (MEAN, SD, SEED1, SEED2, SEED3, NORMSWITCH)
real(dp) function normdist_fn (SEED1, SEED2, SEED3)
real(dp) function normdist2_fn (MEAN, SD, SEED1, SEED2, SEED3)
real(dp) function rad_slope_fn (Declin_rad, Lat_rad, Lat_slope_rad, Inclin_rad, Aspect_rad, Pi)
subroutine rad_slope_day_sub (RAD_BEAM_SLOPE, RAD_DIFF_SLOPE, RAD_TERRA_DAY, DIFFPROP_DAY, SLOPE_RAD, ASPECT_RAD, DECLINATION_RAD, LAT_RAD, SUNRISE, PI)
real(dp) function temp_alt_corr_fn (TEMP, METALT, ALTITUDE)
real(dp) function ppt_rain_fn (TEMP_DAY_MEAN, RAIN_DAY)
real(dp) function ppt_snow_fn (RAIN_DAY, PPT_RAIN)
real(dp) function transnorm_fn (MU, SD, Xval)
real(dp) function normskew_fn (NormVal, Lambda)
real(dp) function tampfromrh_fn (RH)
Function/Subroutine Documentation
angstrom_beta_fn()
real(dp) function metdos::angstrom_beta_fn (real(dp) LATITUDE_RAD)
Definition at line 1866 of file metdos.f90.
azimuth_fn()
real(dp) function metdos::azimuth_fn (real(dp) LATITUDE_RAD, real(dp) DECLINATION, real(dp) SOL_ELEV)
Definition at line 879 of file metdos.f90.
dawn_fn()
real(dp) function metdos::dawn_fn (real(dp) DAYLENGTH)
Definition at line 202 of file metdos.f90.
dawn_hourangle_fn()
real(dp) function metdos::dawn_hourangle_fn (real(dp) DECLINATION, real(dp) LATITUDE_RAD)
Definition at line 502 of file metdos.f90.
Referenced by rad_slope_fn().
day_of_year_fn()
integer function metdos::day_of_year_fn (integer DD, integer MM, integer DAYSINYEAR)
Definition at line 271 of file metdos.f90.
daydata_from_monthdata_fn()
real(dp) function metdos::daydata_from_monthdata_fn (real(dp), dimension(31) MONTHDATA, integer DAY_OF_MONTH)
Definition at line 2946 of file metdos.f90.
daylength2_fn()
real(dp) function metdos::daylength2_fn (real(dp) LATITUDE_RAD, integer DAY_OF_YEAR, real(dp) PI)
Definition at line 448 of file metdos.f90.
daylength_fn()
real(dp) function metdos::daylength_fn (real(dp) LATITUDE_RAD, real(dp) DECLINATION, real(dp) PI)
Definition at line 145 of file metdos.f90.
days_in_month_fn()
integer function metdos::days_in_month_fn (integer MM, integer DAYSINYEAR)
Definition at line 2742 of file metdos.f90.
days_in_year_fn()
integer function metdos::days_in_year_fn (integer YYYY)
Definition at line 346 of file metdos.f90.
declination2_fn()
real(dp) function metdos::declination2_fn (integer DAY_OF_YEAR)
Definition at line 406 of file metdos.f90.
declination_fn()
real(dp) function metdos::declination_fn (integer DAY_OF_YEAR, integer DAYS_IN_YEAR, real(dp) PI)
Definition at line 11 of file metdos.f90.
degree_to_radian_fn()
real(dp) function metdos::degree_to_radian_fn ()
Definition at line 91 of file metdos.f90.
diff_prop_hour_fn()
real(dp) function metdos::diff_prop_hour_fn (real(dp) DIFF_PROP_DAY, real(dp) SOL_ELEV)
Definition at line 2285 of file metdos.f90.
diffprop_day2_fn()
real(dp) function metdos::diffprop_day2_fn (real(dp) TRANS_PROP_DAY, real(dp) BETA)
Definition at line 1904 of file metdos.f90.
diffprop_day_fn()
real(dp) function metdos::diffprop_day_fn (real(dp) TRANS_PROP_DAY)
Definition at line 1020 of file metdos.f90.
dusk_fn()
real(dp) function metdos::dusk_fn (real(dp) DAYLENGTH)
Definition at line 237 of file metdos.f90.
gammadist_fn()
real(dp) function metdos::gammadist_fn (real(dp) A, real(dp) B, real(dp) C, integer SEED1, integer SEED2, integer SEED3)
Definition at line 3626 of file metdos.f90.
References rndf().
Referenced by rain_day_sub(), weather_generator::rain_day_sub_fully_normalised(), and weather_generator::rain_day_sub_normalised().
get_gridsq_sub()
subroutine metdos::get_gridsq_sub (real(dp) GRIDSIZE, real(dp) LATITUDE, real(dp) LONGITUDE, real(dp) GRIDLAT, real(dp) GRIDLONG, real(dp) PI, real(dp) LONG_OFFSET)
Definition at line 3040 of file metdos.f90.
gmt_fn()
real(dp) function metdos::gmt_fn (real(dp) SOLAR_TIME, real(dp) LONGITUDE_RAD, integer DAY_OF_YEAR, real(dp) PI)
Definition at line 1233 of file metdos.f90.
humidity_fn()
real(dp) function metdos::humidity_fn (real(dp) TEMP_AIR_AMPLITUDE)
Definition at line 2990 of file metdos.f90.
humidity_inst_fn()
real(dp) function metdos::humidity_inst_fn (real(dp) VP_UNSAT_BASE, real(dp) VP_SAT_NOW)
Definition at line 1348 of file metdos.f90.
norm_from_rand_fn()
real(dp) function metdos::norm_from_rand_fn (real(dp) MEAN, real(dp) SD, integer SEED1, integer SEED2, integer SEED3, integer NORMSWITCH)
Definition at line 3710 of file metdos.f90.
References normdist2_fn(), normdist_fn(), and transnorm_fn().
Referenced by weather_generator::hum_day_mean2_fn(), temp_day_mean2_fn(), and wind_day_mean_fn().
normdist2_fn()
real(dp) function metdos::normdist2_fn (real(dp) MEAN, real(dp) SD, integer SEED1, integer SEED2, integer SEED3)
Definition at line 3789 of file metdos.f90.
References rndf().
Referenced by norm_from_rand_fn().
normdist_fn()
real(dp) function metdos::normdist_fn (integer SEED1, integer SEED2, integer SEED3)
Definition at line 3741 of file metdos.f90.
References rndf().
Referenced by norm_from_rand_fn().
normskew_fn()
real(dp) function metdos::normskew_fn (real(dp) NormVal, real(dp) Lambda)
Definition at line 4265 of file metdos.f90.
northeast_to_latlong_sub()
subroutine metdos::northeast_to_latlong_sub (real(dp) EASTING, real(dp) NORTHING, real(dp) LATITUDE, real(dp) LONGITUDE, real(dp) PI)
Definition at line 2845 of file metdos.f90.
pivalue_fn()
real(dp) function metdos::pivalue_fn ()
Definition at line 120 of file metdos.f90.
ppt_rain_fn()
real(dp) function metdos::ppt_rain_fn (real(dp) TEMP_DAY_MEAN, real(dp) RAIN_DAY)
Definition at line 4111 of file metdos.f90.
ppt_snow_fn()
real(dp) function metdos::ppt_snow_fn (real(dp) RAIN_DAY, real(dp) PPT_RAIN)
Definition at line 4180 of file metdos.f90.
rad_beam_above_fn()
real(dp) function metdos::rad_beam_above_fn (real(dp) DIFFPROP_DAY, real(dp) RAD_TERRA_DAY, real(dp) ALBEDO_BEAM)
Definition at line 3396 of file metdos.f90.
rad_diff_above_fn()
real(dp) function metdos::rad_diff_above_fn (real(dp) DIFFPROP_DAY, real(dp) RAD_TERRA_DAY, real(dp) ALBEDO_DIFF)
Definition at line 3347 of file metdos.f90.
rad_et_day2_fn()
real(dp) function metdos::rad_et_day2_fn (real(dp) LATITUDE_RAD, real(dp) DECLINATION, real(dp) DAWN_HOURANGLE, real(dp) SOL_ELLIPSE, real(dp) SOL_CONST, real(dp) PI)
Definition at line 545 of file metdos.f90.
rad_et_day3_fn()
real(dp) function metdos::rad_et_day3_fn (real(dp) LATITUDE_RAD, real(dp) DECLINATION, real(dp) SOL_ELLIPSE, real(dp) DAWN, real(dp) DUSK, real(dp) SOL_CONST, real(dp) PI)
Definition at line 691 of file metdos.f90.
References sol_elev_fn().
rad_et_day_fn()
real(dp) function metdos::rad_et_day_fn (real(dp) LATITUDE_RAD, real(dp) DECLINATION, real(dp) DAYLENGTH, real(dp) SOL_ELLIPSE, real(dp) SOL_CONST, real(dp) PI)
Definition at line 612 of file metdos.f90.
References sol_elev_fn().
rad_slope_day_sub()
subroutine metdos::rad_slope_day_sub (real(dp) RAD_BEAM_SLOPE, real(dp) RAD_DIFF_SLOPE, real(dp) RAD_TERRA_DAY, real(dp) DIFFPROP_DAY, real(dp) SLOPE_RAD, real(dp) ASPECT_RAD, real(dp) DECLINATION_RAD, real(dp) LAT_RAD, real(dp) SUNRISE, real(dp) PI)
Definition at line 3987 of file metdos.f90.
rad_slope_fn()
real(dp) function metdos::rad_slope_fn (real(dp) Declin_rad, real(dp) Lat_rad, real(dp) Lat_slope_rad, real(dp) Inclin_rad, real(dp) Aspect_rad, real(dp) Pi)
Definition at line 3904 of file metdos.f90.
References dawn_hourangle_fn().
rad_terra_day_fn()
real(dp) function metdos::rad_terra_day_fn (real(dp) RAD_ET_DAY, real(dp) LATITUDE_RAD, real(dp) CLOUD_COVER, real(dp) BETA)
Definition at line 941 of file metdos.f90.
rad_terra_inst_fn()
real(dp) function metdos::rad_terra_inst_fn (real(dp) DAWN, real(dp) DUSK, real(dp) DAYLENGTH, real(dp) HOUR, real(dp) RAD_TERRA_DAY, real(dp) PI)
Definition at line 1952 of file metdos.f90.
rad_terra_sunday_fn()
real(dp) function metdos::rad_terra_sunday_fn (real(dp) DAYLENGTH, real(dp) SUN_HOURS, real(dp) RAD_ET_DAY)
Definition at line 2119 of file metdos.f90.
rad_to_radpar_fn()
real(dp) function metdos::rad_to_radpar_fn (real(dp) RAD, real(dp) RAD_PERC_PAR)
Definition at line 3174 of file metdos.f90.
radian_from_degree_fn()
real(dp) function metdos::radian_from_degree_fn (real(dp) DEGREES, real(dp) PI)
Definition at line 2807 of file metdos.f90.
radian_to_degree_fn()
real(dp) function metdos::radian_to_degree_fn ()
Definition at line 63 of file metdos.f90.
radpar_to_rad_fn()
real(dp) function metdos::radpar_to_rad_fn (real(dp) RADPAR, real(dp) RAD_PERC_PAR)
Definition at line 3220 of file metdos.f90.
radpar_to_radppfd_fn()
real(dp) function metdos::radpar_to_radppfd_fn (real(dp) RADPAR, real(dp) PPFDCONV)
Definition at line 3265 of file metdos.f90.
radppfd_to_radpar_fn()
real(dp) function metdos::radppfd_to_radpar_fn (real(dp) RADPPFD, real(dp) PPFDCONV)
Definition at line 3306 of file metdos.f90.
rain_day_sub()
subroutine metdos::rain_day_sub (real(dp) NO_RAIN_DAYS, real(dp) RAIN_IN_MONTH, integer DAYS_IN_MONTH, integer SEED1, integer SEED2, integer SEED3, real(dp), dimension(31) RAIN)
Definition at line 1393 of file metdos.f90.
References gammadist_fn(), and rndf().
rain_duration2_sub()
subroutine metdos::rain_duration2_sub (real(dp), dimension(31) RAIN, real(dp), dimension(31) RAIN_DURATION, real(dp), dimension(31) RAIN_INTENSITY, integer DAYS_IN_MONTH, integer IS1, integer IS2, integer IS3)
Definition at line 3445 of file metdos.f90.
References rndf().
rain_duration_sub()
subroutine metdos::rain_duration_sub (real(dp), dimension(31) RAIN, real(dp), dimension(31) RAIN_DURATION, real(dp), dimension(31) RAIN_INTENSITY, integer DAYS_IN_MONTH)
Definition at line 1607 of file metdos.f90.
rndf()
real(dp) function metdos::rndf (real(dp) XLO, real(dp) XHI, integer J1, integer J2, integer J3)
Definition at line 1712 of file metdos.f90.
Referenced by gammadist_fn(), normdist2_fn(), normdist_fn(), rain_day_sub(), weather_generator::rain_day_sub_fully_normalised(), weather_generator::rain_day_sub_normalised(), and rain_duration2_sub().
sol_elev_fn()
real(dp) function metdos::sol_elev_fn (real(dp) LATITUDE_RAD, real(dp) DECLINATION, real(dp) SOLAR_TIME, real(dp) PI)
Definition at line 820 of file metdos.f90.
Referenced by rad_et_day3_fn(), and rad_et_day_fn().
solar_ellipse2_fn()
real(dp) function metdos::solar_ellipse2_fn (integer DAY_OF_YEAR)
Definition at line 1133 of file metdos.f90.
solar_ellipse_fn()
real(dp) function metdos::solar_ellipse_fn (integer DAY_OF_YEAR, integer DAYS_IN_YEAR, real(dp) PI)
Definition at line 1077 of file metdos.f90.
solar_time_fn()
real(dp) function metdos::solar_time_fn (real(dp) GMT, real(dp) LONGITUDE_RAD, integer DAY_OF_YEAR, real(dp) PI)
Definition at line 1170 of file metdos.f90.
tampfromrh_fn()
real(dp) function metdos::tampfromrh_fn (real(dp) RH)
Definition at line 4307 of file metdos.f90.
temp_air_amplitude2_fn()
real(dp) function metdos::temp_air_amplitude2_fn (real(dp) TEMP_MAX_DAY, real(dp) TEMP_MIN_DAY)
Definition at line 2442 of file metdos.f90.
temp_air_amplitude_fn()
real(dp) function metdos::temp_air_amplitude_fn (real(dp) TRANS_PROP_DAY, real(dp) A_SKY, real(dp) ANGSTROM_BETA, real(dp) C_SKY)
Definition at line 2216 of file metdos.f90.
temp_alt_corr_fn()
real(dp) function metdos::temp_alt_corr_fn (real(dp) TEMP, real(dp) METALT, real(dp) ALTITUDE)
Definition at line 4067 of file metdos.f90.
temp_day_mean2_fn()
real(dp) function metdos::temp_day_mean2_fn (real(dp) TEMP_MEAN_MONTH, real(dp) TEMP_SD_MONTH, real(dp) TEMP_AUTOCORR_MONTH, real(dp) TEMP_YESTERDAY, integer IS1, integer IS2, integer IS3, integer NORMSWITCH)
Definition at line 2524 of file metdos.f90.
References norm_from_rand_fn().
Referenced by weather_generator::ex_clim_weather_generator().
temp_day_mean_fn()
real(dp) function metdos::temp_day_mean_fn (real(dp) TEMP_MAX_DAY, real(dp) TEMP_MIN_DAY)
Definition at line 2483 of file metdos.f90.
temp_hour_fn()
real(dp) function metdos::temp_hour_fn (real(dp) HOUR, real(dp) TEMPMAX, real(dp) TEMPMIN, real(dp) PI)
Definition at line 1295 of file metdos.f90.
temp_max_day_fn()
real(dp) function metdos::temp_max_day_fn (real(dp) TEMP_AIR_AMPLITUDE, real(dp) TEMP_DAY_MEAN)
Definition at line 2357 of file metdos.f90.
temp_min_day_fn()
real(dp) function metdos::temp_min_day_fn (real(dp) TEMP_AIR_AMPLITUDE, real(dp) TEMP_DAY_MEAN)
Definition at line 2400 of file metdos.f90.
trans_prop_day2_fn()
real(dp) function metdos::trans_prop_day2_fn (real(dp) TEMP_AIR_AMPLITUDE, real(dp) A_SKY, real(dp) ANGSTROM_BETA, real(dp) C_SKY)
Definition at line 3557 of file metdos.f90.
trans_prop_day_fn()
real(dp) function metdos::trans_prop_day_fn (real(dp) RAD_ET_DAY, real(dp) RAD_TERRA_SW_DAY)
Definition at line 1819 of file metdos.f90.
transnorm_fn()
real(dp) function metdos::transnorm_fn (real(dp) MU, real(dp) SD, real(dp) Xval)
Definition at line 4219 of file metdos.f90.
Referenced by norm_from_rand_fn().
vp_sat2_fn()
real(dp) function metdos::vp_sat2_fn (real(dp) TEMP_C)
Definition at line 3515 of file metdos.f90.
vp_sat_fn()
real(dp) function metdos::vp_sat_fn (real(dp) TEMP_C)
Definition at line 786 of file metdos.f90.
vp_unsat2_fn()
real(dp) function metdos::vp_unsat2_fn (real(dp) VP_SAT, real(dp) HUMIDITY)
Definition at line 3131 of file metdos.f90.
wind_day_mean_fn()
real(dp) function metdos::wind_day_mean_fn (real(dp) WIND_MONTH_MEAN, real(dp) WIND_SD_MONTH, real(dp) WIND_AUTOCORR_MONTH, real(dp) WIND_YESTERDAY, integer IS1, integer IS2, integer IS3, integer NORMSWITCH)
Definition at line 2601 of file metdos.f90.
References norm_from_rand_fn().
windspeed_inst_fn()
real(dp) function metdos::windspeed_inst_fn (real(dp) WIND_RUN_DAY, real(dp) HOUR)
Definition at line 2026 of file metdos.f90.