SDGVM Update Project: doly Module Reference
doly Module Reference
Collection of subroutines to read in data.
Functions/Subroutines
subroutine dolyday (tmp, prc, hum, cld, ca, soilc, soiln, minn, adp, sfc, sw, sswc, awl, kd, kx, daygpp, resp_l, rlai, evap, tran, roff, interc, evbs, flow1, flow2, pet, ht, ft, lmor_sc, nleaf, leaflitter, hrs, q, qdirect, qdiff, fpr, tleaf_n, tleaf_p, canga, gsn, rn, ce_light, ce_ci, ce_t, ce_maxlight, ce_ga, ce_rh, check_closure, par_loops, lat, year, mnth, day, thty_dys, gs_type, swr)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine evapotranspiration (t, rh, rn, canga, gsn, hrs, eemm, etmm)
Calculate evapotranspiration.
Detailed Description
Collection of subroutines to read in data.
Author
Mark Lomas
Date
July 2016
Function/Subroutine Documentation
dolyday()
subroutine doly::dolyday (real(dp) tmp, real(dp) prc, real(dp) hum, real(dp) cld, real(dp) ca, real(dp) soilc, real(dp) soiln, real(dp) minn, real(dp), dimension(4) adp, real(dp), dimension(4) sfc, real(dp), dimension(4) sw, real(dp), dimension(4) sswc, real(dp), dimension(4) awl, real(dp) kd, real(dp) kx, real(dp) daygpp, real(dp) resp_l, real(dp) rlai, real(dp) evap, real(dp) tran, real(dp) roff, real(dp) interc, real(dp) evbs, real(dp) flow1, real(dp) flow2, real(dp) pet, real(dp) ht, integer ft, real(dp), dimension(3600) lmor_sc, real(dp) nleaf, real(dp) leaflitter, real(dp) hrs, real(dp) q, real(dp) qdirect, real(dp) qdiff, real(dp) fpr, real(dp) tleaf_n, real(dp) tleaf_p, real(dp) canga, real(dp) gsn, real(dp) rn, real(dp), dimension(30,12) ce_light, real(dp), dimension(30,12) ce_ci, real(dp), dimension(30) ce_t, real(dp), dimension(30,12) ce_maxlight, real(dp), dimension(30,12) ce_ga, real(dp), dimension(30) ce_rh, logical check_closure, integer par_loops, real(dp) lat, integer year, integer mnth, integer day, integer thty_dys, integer gs_type, real(dp) swr)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 44 of file doly.f90.
References productivity_methods::nppcalc(), site_parameters::ssp, system_state::ssv, phenology_methods::suma_add(), and tuning_parameters::tgp.
Referenced by sdgvm().
evapotranspiration()
subroutine doly::evapotranspiration (real(dp) t, real(dp) rh, real(dp) rn, real(dp) canga, real(dp) gsn, real(dp) hrs, real(dp) eemm, real(dp) etmm)
Calculate evapotranspiration.
etmm is transpiration,eemm evaporation
Author
Mark Lomas
Date
Feb 2006
Definition at line 369 of file doly.f90.
References misc_values::msv, site_parameters::ssp, system_state::ssv, and tuning_parameters::tgp.
Referenced by sdgvm().