SDGVM Update Project: open_files Module Reference
open_files Module Reference
Functions/Subroutines
subroutine open_diag ()
Open diagnostic file.
subroutine open_snapshots (snp_no, snpshts)
Open snapshot files file.
subroutine open_default ()
Open default output files.
subroutine open_optional (out_cov, out_bio, out_bud, out_sen)
Open optional output files.
subroutine open_tile_pft ()
Open input and/or output files for state vector.
subroutine open_state ()
Open input and/or output files for state vector.
subroutine open_site_info ()
Write lat & lon for output files.
subroutine write_lat_lon (lat, lon, nft, out_cov, out_bio, out_bud, out_sen, oymdft, otagsn, oymd, otagsnft, outyears1, outyears2)
Write lat & lon for output files.
Function/Subroutine Documentation
open_default()
subroutine open_files::open_default ()
Open default output files.
These files will contain yearly values.
Author
Mark Lomas
Date
Feb 2006
Definition at line 102 of file open_files.f90.
References file_object::fun.
open_diag()
subroutine open_files::open_diag ()
Open diagnostic file.
This is used to report any potential errors.
Author
Mark Lomas
Date
Feb 2006
Definition at line 27 of file open_files.f90.
References file_object::fun.
Referenced by read_input::process_input_file().
open_optional()
subroutine open_files::open_optional (logical out_cov, logical out_bio, logical out_bud, logical out_sen)
Open optional output files.
Author
Mark Lomas
Date
Feb 2006
Definition at line 154 of file open_files.f90.
References file_object::fun, and pft_parameters::pft_tab.
open_site_info()
subroutine open_files::open_site_info ()
Write lat & lon for output files.
Author
Mark Lomas
Date
Feb 2006
Definition at line 320 of file open_files.f90.
References file_object::fun, and pft_parameters::pft_tab.
open_snapshots()
subroutine open_files::open_snapshots (integer snp_no, integer, dimension(max_years) snpshts)
Open snapshot files file.
These files contain the entire system state for the final day of the years given in the input files. The files can be used the make site 'cartoons' using the utility sorfware.
Author
Mark Lomas
Date
Feb 2006
Definition at line 56 of file open_files.f90.
References func::in2st(), and func::stripb().
Referenced by read_input::process_input_file().
open_state()
subroutine open_files::open_state ()
Open input and/or output files for state vector.
Opens input and/or output files for state vector
Author
Mark Lomas
Date
Feb 2006
Definition at line 268 of file open_files.f90.
References file_object::fun.
open_tile_pft()
subroutine open_files::open_tile_pft ()
Open input and/or output files for state vector.
Opens input and/or output files for state vector
Author
Mark Lomas
Date
Feb 2006
Definition at line 194 of file open_files.f90.
References file_object::fun, and pft_parameters::pft_tab.
write_lat_lon()
subroutine open_files::write_lat_lon (real(dp) lat, real(dp) lon, integer nft, logical out_cov, logical out_bio, logical out_bud, logical out_sen, integer oymdft, integer, dimension(max_outputs) otagsn, integer oymd, integer, dimension(max_outputs) otagsnft, integer outyears1, integer outyears2)
Write lat & lon for output files.
Author
Mark Lomas
Date
Feb 2006
Definition at line 352 of file open_files.f90.
References file_class::filename_base(), and file_object::fun.