SDGVM Update Project: read_input Module Reference
read_input Module Reference
Functions/Subroutines
subroutine process_input_file (buff1, xlatf, xlon0, xlatres, xlonres, speedc, xspeedc, crand, outyears, nyears, yr0, yrf, yearind, idum, yearv, nomdos, otags, omav, ofmt_daily, ofmt_monthly, ofmt_yearly, outyears1, outyears2, oymd, otagsn, otagsnft, snpshts, snp_no, out_cov, out_bio, out_bud, out_sen, lutab, grassrc, barerc, fireres, luse, l_b_and_c, soil_chr, topsl, defaulttopsl, sites, latdel, londel, lat_lon, day_mnth, thty_dys, xlatresn, xlonresn, ilanduse, nft, xyear0, xyearf, lmor_sc, oymdft, iofnft, sit_grd, du, narg, fire_ant, harvest_ant, met_seq, par_loops)
subroutine read_param (stver)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Function/Subroutine Documentation
process_input_file()
subroutine read_input::process_input_file (character(len=80) buff1, real(dp) xlatf, real(dp) xlon0, real(dp) xlatres, real(dp) xlonres, logical speedc, logical xspeedc, logical crand, integer outyears, integer nyears, integer yr0, integer yrf, integer, dimension(max_years) yearind, integer idum, integer, dimension(max_years) yearv, integer nomdos, character(len=str_len), dimension(max_outputs) otags, integer, dimension(max_outputs) omav, character(len=str_len), dimension(max_outputs) ofmt_daily, character(len=str_len), dimension(max_outputs) ofmt_monthly, character(len=str_len), dimension(max_outputs) ofmt_yearly, integer outyears1, integer outyears2, integer oymd, integer, dimension(max_outputs) otagsn, integer, dimension(max_outputs) otagsnft, integer, dimension(max_years) snpshts, integer snp_no, logical out_cov, logical out_bio, logical out_bud, logical out_sen, real(dp), dimension(255,100) lutab, real(dp) grassrc, real(dp) barerc, integer fireres, integer, dimension(max_years) luse, logical l_b_and_c, real(dp), dimension(10) soil_chr, real(dp) topsl, real(dp) defaulttopsl, integer sites, real(dp) latdel, real(dp) londel, real(dp), dimension(max_sites,2) lat_lon, integer day_mnth, integer thty_dys, integer xlatresn, integer xlonresn, integer ilanduse, integer nft, integer xyear0, integer xyearf, real(dp), dimension(3600,max_cohorts) lmor_sc, integer oymdft, integer iofnft, integer sit_grd, integer du, integer narg, logical, dimension(max_years) fire_ant, logical, dimension(max_years) harvest_ant, logical met_seq, integer par_loops)
Author
Mark Lomas
Date
Feb 2006
Definition at line 49 of file read_input.f90.
References sdgvm1::land_site_check(), open_files::open_diag(), open_files::open_snapshots(), sdgvm1::output_options(), pft_parameters::pft_tab, func::randomv(), sdgvm1::set_pixel_out(), sdgvm1::set_subpixel_out(), site_parameters::ssp, func::stcmp(), func::stripbs(), and tuning_parameters::tgp.
Referenced by sdgvm().
read_param()
subroutine read_input::read_param (character(len=str_len) stver)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
First reads misc_params.dat file in /f03 with input on year step to output on screen and whether run is regional or country.Saved in msp structure defined in misc_parameters.f90. It then reads the param.dat file in /inc with the tuning parameters and saves in structure tgp defined in tuning_parameters.f90.
Author
Mark Lomas
Date
Feb 2006
Definition at line 1116 of file read_input.f90.
References func::blank(), misc_parameters::msp, func::stcmp(), func::stripb(), func::stripbs(), and tuning_parameters::tgp.
Referenced by sdgvm().