SDGVM Update Project: soil_methods Module Reference
soil_methods Module Reference
Functions/Subroutines
subroutine soil_dynamics2 (pet, prc, tmp, flow1, flow2, nfix, nci, sresp, lch, ca, site, year, yr0, yrf, speedc, ft, check_closure)
subroutine soil_dynamics (avmnpet, avmnppt, avmnt, h2o, flow1, flow2, nfix, nci, srespm, lchm, ca, site, year, yr0, yrf, speedc, ft, check_closure)
subroutine fcap (ts, tc, adp, sfc, sw)
subroutine setcenpar (ts, tc, pet, ppt, tmp, h2o, flow2, slnr, rlnr, ar, fms, fmr, scl, rcl, tm, ft, cal, cap, cas, csp, csa, kr)
subroutine soilcloss (c, tot, scl, kr, rcl, ft, cal)
subroutine cdyn (c0, c1, t0, t1, slc, rlc, scl, rcl, kr, csa, cas, csp, cap, cal, fms, fmr, ft, sresp, lch, year, yr0, yrf, speedc)
subroutine diffeq (t01, t11, c1, cp, cjac, sresp, lch)
subroutine der (c, f)
subroutine pder (jac)
subroutine clsasi (tex, tc, ts, tsi)
subroutine ndyn (n0, n, minn, t0, t1, fl, c, flow1, flow2, ts, ml, al, scn, nfix, cal, nci, site)
subroutine nbal (c, tn, x, scn, nci)
subroutine flows (c0, c, t0, t1, fl, slc, rlc, scl, rcl, fms, fmr, csa, csp, cas, cap)
real(dp) function ncrata (x)
real(dp) function ncrats (x)
real(dp) function ncratp (x)
real(dp) function ncratsm (x)
real(dp) function eot (x)
real(dp) function eot1 (x)
real(dp) function eow (x)
real(dp) function eow1 (x)
subroutine wsparam (l_b_and_c, nupc, awl, kd, kx, nci, nfix, adp, topsl, sfc, sw, sswc)
Function/Subroutine Documentation
cdyn()
subroutine soil_methods::cdyn (real(dp), dimension(8) c0, real(dp), dimension(8) c1, real(dp) t0, real(dp) t1, real(dp) slc, real(dp) rlc, real(dp) scl, real(dp) rcl, real(dp), dimension(8) kr, real(dp) csa, real(dp) cas, real(dp) csp, real(dp) cap, real(dp) cal, real(dp) fms, real(dp) fmr, real(dp) ft, real(dp) sresp, real(dp) lch, integer year, integer yr0, integer yrf, logical speedc)
Definition at line 455 of file soil_methods.f90.
References der(), diffeq(), and pder().
Referenced by soil_dynamics().
clsasi()
subroutine soil_methods::clsasi (integer tex, real(dp) tc, real(dp) ts, real(dp) tsi)
Definition at line 680 of file soil_methods.f90.
der()
subroutine soil_methods::der (real(dp), dimension(8) c, real(dp), dimension(10) f)
Definition at line 563 of file soil_methods.f90.
Referenced by cdyn().
diffeq()
subroutine soil_methods::diffeq (real(dp) t01, real(dp) t11, real(dp), dimension(8) c1, real(dp), dimension(10) cp, real(dp), dimension(10,10) cjac, real(dp) sresp, real(dp) lch)
Definition at line 522 of file soil_methods.f90.
Referenced by cdyn().
eot()
real(dp) function soil_methods::eot (real(dp) x)
Definition at line 1161 of file soil_methods.f90.
Referenced by setcenpar().
eot1()
real(dp) function soil_methods::eot1 (real(dp) x)
Definition at line 1199 of file soil_methods.f90.
eow()
real(dp) function soil_methods::eow (real(dp) x)
Definition at line 1225 of file soil_methods.f90.
Referenced by setcenpar().
eow1()
real(dp) function soil_methods::eow1 (real(dp) x)
Definition at line 1267 of file soil_methods.f90.
fcap()
subroutine soil_methods::fcap (real(dp) ts, real(dp) tc, real(dp), dimension(4) adp, real(dp), dimension(4) sfc, real(dp), dimension(4) sw)
Definition at line 252 of file soil_methods.f90.
flows()
subroutine soil_methods::flows (real(dp), dimension(8) c0, real(dp), dimension(8) c, real(dp) t0, real(dp) t1, real(dp), dimension(14) fl, real(dp) slc, real(dp) rlc, real(dp) scl, real(dp) rcl, real(dp) fms, real(dp) fmr, real(dp) csa, real(dp) csp, real(dp) cas, real(dp) cap)
Definition at line 977 of file soil_methods.f90.
Referenced by soil_dynamics().
nbal()
subroutine soil_methods::nbal (real(dp), dimension(8) c, real(dp) tn, real(dp) x, real(dp) scn, real(dp), dimension(4) nci)
Definition at line 887 of file soil_methods.f90.
References ncratsm().
Referenced by ndyn().
ncrata()
real(dp) function soil_methods::ncrata (real(dp) x)
Definition at line 1040 of file soil_methods.f90.
Referenced by ndyn().
ncratp()
real(dp) function soil_methods::ncratp (real(dp) x)
Definition at line 1100 of file soil_methods.f90.
Referenced by ndyn().
ncrats()
real(dp) function soil_methods::ncrats (real(dp) x)
Definition at line 1070 of file soil_methods.f90.
Referenced by ndyn().
ncratsm()
real(dp) function soil_methods::ncratsm (real(dp) x)
Definition at line 1130 of file soil_methods.f90.
Referenced by nbal(), and ndyn().
ndyn()
subroutine soil_methods::ndyn (real(dp), dimension(8) n0, real(dp), dimension(8) n, real(dp), dimension(3) minn, real(dp) t0, real(dp) t1, real(dp), dimension(14) fl, real(dp), dimension(8) c, real(dp) flow1, real(dp) flow2, real(dp) ts, real(dp) ml, real(dp) al, real(dp) scn, real(dp) nfix, real(dp) cal, real(dp), dimension(4) nci, integer site)
Definition at line 732 of file soil_methods.f90.
References file_object::fun, nbal(), ncrata(), ncratp(), ncrats(), and ncratsm().
Referenced by soil_dynamics().
pder()
subroutine soil_methods::pder (real(dp), dimension(10,10) jac)
Definition at line 606 of file soil_methods.f90.
Referenced by cdyn().
setcenpar()
subroutine soil_methods::setcenpar (real(dp) ts, real(dp) tc, real(dp) pet, real(dp) ppt, real(dp) tmp, real(dp) h2o, real(dp) flow2, real(dp) slnr, real(dp) rlnr, real(dp) ar, real(dp) fms, real(dp) fmr, real(dp) scl, real(dp) rcl, real(dp) tm, real(dp) ft, real(dp) cal, real(dp) cap, real(dp) cas, real(dp) csp, real(dp) csa, real(dp), dimension(8) kr)
Definition at line 364 of file soil_methods.f90.
References eot(), eow(), and tuning_parameters::tgp.
Referenced by soil_dynamics().
soil_dynamics()
subroutine soil_methods::soil_dynamics (real(dp) avmnpet, real(dp) avmnppt, real(dp) avmnt, real(dp) h2o, real(dp) flow1, real(dp) flow2, real(dp) nfix, real(dp), dimension(4) nci, real(dp) srespm, real(dp) lchm, real(dp) ca, integer site, integer year, integer yr0, integer yrf, logical speedc, integer ft, logical check_closure)
Definition at line 99 of file soil_methods.f90.
References cdyn(), flows(), ndyn(), setcenpar(), and state_methods::sum_carbon().
Referenced by soil_dynamics2().
soil_dynamics2()
subroutine soil_methods::soil_dynamics2 (real(dp) pet, real(dp) prc, real(dp) tmp, real(dp) flow1, real(dp) flow2, real(dp) nfix, real(dp), dimension(4) nci, real(dp) sresp, real(dp) lch, real(dp) ca, integer site, integer year, integer yr0, integer yrf, logical speedc, integer ft, logical check_closure)
Definition at line 25 of file soil_methods.f90.
References misc_values::msv, and soil_dynamics().
Referenced by sdgvm().
soilcloss()
subroutine soil_methods::soilcloss (real(dp), dimension(8) c, real(dp) tot, real(dp) scl, real(dp), dimension(8) kr, real(dp) rcl, real(dp) ft, real(dp) cal)
Definition at line 425 of file soil_methods.f90.
wsparam()
subroutine soil_methods::wsparam (logical l_b_and_c, real(dp) nupc, real(dp), dimension(4) awl, real(dp) kd, real(dp) kx, real(dp), dimension(4) nci, real(dp) nfix, real(dp), dimension(4) adp, real(dp) topsl, real(dp), dimension(4) sfc, real(dp), dimension(4) sw, real(dp), dimension(4) sswc)
Definition at line 1299 of file soil_methods.f90.
Referenced by sdgvm().