SDGVM Update Project: weather_generator Module Reference
weather_generator Module Reference
Functions/Subroutines
subroutine ex_clim_weather_generator (lat, lon, xlatf, xlatres, xlatresn, xlon0, xlonres, xlonresn, yr0, yrf, tmpv, humv, prcv, mcldv, swrv, isite, year0, yearf, du, seed1, seed2, seed3, l_clim, l_stats, read_par)
subroutine read_wg_file (du, filename, values, lon, lat, l_stats)
real(dp) function floatingmean (day, mnth, year, lastyear, array)
real(dp) function floatingmean2 (day, mnth, year, lastyear, array)
subroutine rain_day_sub_fully_normalised (NO_RAIN_DAYS, RAIN_IN_MONTH, DAYS_IN_MONTH, SEED1, SEED2, SEED3, RAIN)
subroutine rain_day_sub_normalised (NO_RAIN_DAYS, RAIN_IN_MONTH, DAYS_IN_MONTH, SEED1, SEED2, SEED3, RAIN)
real(dp) function hum_day_mean2_fn (HUM_MEAN_MONTH, HUM_SD_MONTH, HUM_AUTOCORR_MONTH, HUM_YESTERDAY, IS1, IS2, IS3, NORMSWITCH)
subroutine mean_pres (iyear, mswrv, swrv)
Function/Subroutine Documentation
ex_clim_weather_generator()
subroutine weather_generator::ex_clim_weather_generator (real(dp) lat, real(dp) lon, real(dp) xlatf, real(dp) xlatres, integer xlatresn, real(dp) xlon0, real(dp) xlonres, integer xlonresn, integer yr0, integer yrf, real(dp), dimension(500,12,31) tmpv, real(dp), dimension(500,12,31) humv, real(dp), dimension(500,12,31) prcv, real(dp), dimension(500,12) mcldv, real(dp), dimension(500,12,31) swrv, integer isite, integer year0, integer yearf, integer du, integer seed1, integer seed2, integer seed3, logical l_clim, logical l_stats, logical read_par)
Definition at line 20 of file weather_generator.f90.
References data::bi_lin(), floatingmean2(), hum_day_mean2_fn(), mean_pres(), rain_day_sub_fully_normalised(), read_wg_file(), and metdos::temp_day_mean2_fn().
Referenced by sdgvm1::read_climate().
floatingmean()
real(dp) function weather_generator::floatingmean (integer day, integer mnth, integer year, integer lastyear, integer, dimension(500,12) array)
Definition at line 483 of file weather_generator.f90.
floatingmean2()
real(dp) function weather_generator::floatingmean2 (integer day, integer mnth, integer year, integer lastyear, real(dp), dimension(500,12) array)
Definition at line 528 of file weather_generator.f90.
Referenced by ex_clim_weather_generator().
hum_day_mean2_fn()
real(dp) function weather_generator::hum_day_mean2_fn (real(dp) HUM_MEAN_MONTH, real(dp) HUM_SD_MONTH, real(dp) HUM_AUTOCORR_MONTH, real(dp) HUM_YESTERDAY, integer IS1, integer IS2, integer IS3, integer NORMSWITCH)
Definition at line 963 of file weather_generator.f90.
References metdos::norm_from_rand_fn().
Referenced by ex_clim_weather_generator().
mean_pres()
subroutine weather_generator::mean_pres (integer iyear, real(dp), dimension(500,12) mswrv, real(dp), dimension(500,12,31) swrv)
Definition at line 1042 of file weather_generator.f90.
Referenced by ex_clim_weather_generator().
rain_day_sub_fully_normalised()
subroutine weather_generator::rain_day_sub_fully_normalised (real(dp) NO_RAIN_DAYS, real(dp) RAIN_IN_MONTH, integer DAYS_IN_MONTH, integer SEED1, integer SEED2, integer SEED3, real(dp), dimension(31) RAIN)
Definition at line 576 of file weather_generator.f90.
References metdos::gammadist_fn(), and metdos::rndf().
Referenced by ex_clim_weather_generator().
rain_day_sub_normalised()
subroutine weather_generator::rain_day_sub_normalised (real(dp) NO_RAIN_DAYS, real(dp) RAIN_IN_MONTH, integer DAYS_IN_MONTH, integer SEED1, integer SEED2, integer SEED3, real(dp), dimension(31) RAIN)
Definition at line 721 of file weather_generator.f90.
References metdos::gammadist_fn(), and metdos::rndf().
read_wg_file()
subroutine weather_generator::read_wg_file (integer du, character(len=str_len) filename, real(dp), dimension(12) values, real(dp) lon, real(dp) lat, logical l_stats)
Definition at line 380 of file weather_generator.f90.
References data::bi_lin().
Referenced by ex_clim_weather_generator().