SDGVM Update Project: luna_methods Module Reference
luna_methods Module Reference
Functions/Subroutines
subroutine luna (z, vcmx25_z, jmx25_z, PNlc_z, enzs_z, rb10, sla, lnc, par240d, par240x, CO2a10, o2a10, hourpd, relh10_in, tair10, gs_func, ftg0, ftg1, max_daily_pchg, ttype, ftToptV, ftHaV, ftHdV, ftToptJ, ftHaJ, ftHdJ)
subroutine luna_ninvestments (KcKjFlag, FNCa, Nlc, forc_pbot10, relh10, CO2a10, O2a10, PARi10, PARimx10, rb10, hourpd, tair10, tleafd10, tleafn10, Kj2Kc, Wc2Wjb0, JmaxCoef, Fc, Fj, NUEc, NUEj, NUEcref, NUEjref, NUEr, Kc, Kj, ci, Vcmax, Jmax, JmeanL, JmaxL, Net, Ncb, Nresp, PSN, RESP, gs_func, ftg0, ftg1)
subroutine nue (o2a, ci, tgrow, tleaf, NUEj, NUEc, Kj2Kc, ttype, ftToptV, ftHaV, ftHdV, ftToptJ, ftHaJ, ftHdJ)
real(dp) function resptbernacchi (tleaf)
subroutine luna_nogrowth (max_daily_pchg, vcmx25_z, jmx25_z, enzs_z)
Function/Subroutine Documentation
luna()
subroutine luna_methods::luna (integer, intent(in) z, real(dp), intent(inout) vcmx25_z, real(dp), intent(inout) jmx25_z, real(dp), intent(inout) PNlc_z, real(dp), intent(inout) enzs_z, real(dp), intent(in) rb10, real(dp), intent(in) sla, real(dp), intent(in) lnc, real(dp), intent(in) par240d, real(dp), intent(in) par240x, real(dp), intent(in) CO2a10, real(dp), intent(in) o2a10, real(dp), intent(in) hourpd, real(dp), intent(in) relh10_in, real(dp), intent(in) tair10, integer, intent(in) gs_func, real(dp), intent(in) ftg0, real(dp), intent(in) ftg1, real(dp), intent(in) max_daily_pchg, integer, intent(in) ttype, real(dp), intent(in) ftToptV, real(dp), intent(in) ftHaV, real(dp), intent(in) ftHdV, real(dp), intent(in) ftToptJ, real(dp), intent(in) ftHaJ, real(dp), intent(in) ftHdJ)
Definition at line 42 of file luna_methods.f90.
References luna_ninvestments(), nue(), resptbernacchi(), and productivity_luna_methods::t_scalar().
Referenced by productivity_methods::nppcalc().
luna_ninvestments()
subroutine luna_methods::luna_ninvestments (integer, intent(in) KcKjFlag, real(dp), intent(in) FNCa, real(dp), intent(in) Nlc, real(dp), intent(in) forc_pbot10, real(dp), intent(in) relh10, real(dp), intent(in) CO2a10, real(dp), intent(in) O2a10, real(dp), intent(in) PARi10, real(dp), intent(in) PARimx10, real(dp), intent(in) rb10, real(dp), intent(in) hourpd, real(dp), intent(in) tair10, real(dp), intent(in) tleafd10, real(dp), intent(in) tleafn10, real(dp), intent(in) Kj2Kc, real(dp), intent(in) Wc2Wjb0, real(dp), intent(in) JmaxCoef, real(dp), intent(in) Fc, real(dp), intent(in) Fj, real(dp), intent(in) NUEc, real(dp), intent(in) NUEj, real(dp), intent(in) NUEcref, real(dp), intent(in) NUEjref, real(dp), intent(in) NUEr, real(dp), intent(inout) Kc, real(dp), intent(inout) Kj, real(dp), intent(inout) ci, real(dp), intent(out) Vcmax, real(dp), intent(out) Jmax, real(dp), intent(out) JmeanL, real(dp), intent(out) JmaxL, real(dp), intent(out) Net, real(dp), intent(out) Ncb, real(dp), intent(out) Nresp, real(dp), intent(out) PSN, real(dp), intent(out) RESP, integer, intent(in) gs_func, real(dp), intent(in) ftg0, real(dp), intent(in) ftg1)
Definition at line 467 of file luna_methods.f90.
Referenced by luna().
luna_nogrowth()
subroutine luna_methods::luna_nogrowth (real(dp), intent(in) max_daily_pchg, real(dp), intent(inout) vcmx25_z, real(dp), intent(inout) jmx25_z, real(dp), intent(inout) enzs_z)
Definition at line 755 of file luna_methods.f90.
Referenced by productivity_methods::nppcalc().
nue()
subroutine luna_methods::nue (real(dp), intent(in) o2a, real(dp), intent(in) ci, real(dp), intent(in) tgrow, real(dp), intent(in) tleaf, real(dp), intent(out) NUEj, real(dp), intent(out) NUEc, real(dp), intent(out) Kj2Kc, integer ttype, real(dp), intent(in) ftToptV, real(dp), intent(in) ftHaV, real(dp), intent(in) ftHdV, real(dp), intent(in) ftToptJ, real(dp), intent(in) ftHaJ, real(dp), intent(in) ftHdJ)
Definition at line 656 of file luna_methods.f90.
References productivity_luna_methods::t_scalar().
Referenced by luna().
resptbernacchi()
real(dp) function luna_methods::resptbernacchi (real(dp), intent(in) tleaf)
Definition at line 737 of file luna_methods.f90.
Referenced by luna().