SDGVM Update Project: file_class Module Reference
file_class Module Reference
Data Types
type noids
Functions/Subroutines
subroutine filename_base (st1, st2)
integer function get_id (this, filename)
integer function get_id_n (this, n)
subroutine open_old (this, filename, fid)
subroutine openu_old (this, filename, fid)
subroutine open (this, filename, fid)
subroutine openu (this, filename, fid)
subroutine close_name (this, filename)
subroutine close_n (this, n_id)
subroutine close (this, id)
subroutine print (this)
Variables
integer max_files
Function/Subroutine Documentation
close()
subroutine file_class::close (class(noids) this, integer id)
Definition at line 288 of file file_io_methods.f90.
close_n()
subroutine file_class::close_n (class(noids) this, integer n_id)
Definition at line 266 of file file_io_methods.f90.
close_name()
subroutine file_class::close_name (class(noids) this, character(len=*) filename)
Definition at line 230 of file file_io_methods.f90.
filename_base()
subroutine file_class::filename_base (character(len=*) st1, character(len=*) st2)
Definition at line 35 of file file_io_methods.f90.
Referenced by get_id(), and open_files::write_lat_lon().
get_id()
integer function file_class::get_id (class(noids) this, character(len=*) filename)
Definition at line 55 of file file_io_methods.f90.
References filename_base().
get_id_n()
integer function file_class::get_id_n (class(noids) this, integer n)
Definition at line 89 of file file_io_methods.f90.
open()
subroutine file_class::open (class(noids) this, character(len=*) filename, integer fid)
Definition at line 167 of file file_io_methods.f90.
References max_files.
open_old()
subroutine file_class::open_old (class(noids) this, character(len=*) filename, integer fid)
Definition at line 104 of file file_io_methods.f90.
References max_files.
openu()
subroutine file_class::openu (class(noids) this, character(len=*) filename, integer fid)
Definition at line 198 of file file_io_methods.f90.
References max_files.
openu_old()
subroutine file_class::openu_old (class(noids) this, character(len=*) filename, integer fid)
Definition at line 135 of file file_io_methods.f90.
References max_files.
print()
subroutine file_class::print (class(noids) this)
Definition at line 323 of file file_io_methods.f90.
Referenced by sdgvm().
Variable Documentation
max_files
integer file_class::max_files
Definition at line 9 of file file_io_methods.f90.
Referenced by open(), open_old(), openu(), and openu_old().