SDGVM Update Project: data Module Reference
data Module Reference
Collection of subroutines to read in data.
Functions/Subroutines
subroutine ex_clim (lat, lon, xlatf, xlatres, xlatresn, xlon0, xlonres, xlonresn, yr0, yrf, tmpv, humv, prcv, isite, year0, yearf, siteno, du, read_par)
Extract climate data from the climate database for the nearest site.
subroutine ex_clim_site (yr0, yrf, tmpv, humv, prcv, year0, yearf)
Extract climate data from the climate database for the nearest site.
subroutine ex_soil (lat, lon, sol_chr2, du, l_soil)
Extract % sand % silt bulk density and depth from soils database.
subroutine ex_lu (lat, lon, luse, yr0, yrf, du)
Extract land use.
subroutine ex_clu (lat, lon, nft, lutab, cluse, yr0, yrf, du, l_lu)
subroutine lorc (du, lat, lon, latdel, londel, xx)
Determine if the site is a land site.
subroutine base72i (c, x)
integer function n7 (x)
subroutine bi_lin (xx, indx, xnorm, ynorm, ans)
Performs bilinear interpolation between four points.
subroutine readco2 (yr0, yrf, co2, daily_co2, nyears)
Reads co2 values for each year.
subroutine landuse1 (luse, yr0, yrf, fire_ant, harvest_ant)
Detailed Description
Collection of subroutines to read in data.
Author
Mark Lomas
Date
July 2016
Function/Subroutine Documentation
base72i()
subroutine data::base72i (character c, integer, dimension(7) x)
Author
Mark Lomas
Date
Feb 2006
Definition at line 950 of file data.f90.
Referenced by lorc().
bi_lin()
subroutine data::bi_lin (real(dp), dimension(4,4) xx, integer, dimension(4,4) indx, real(dp) xnorm, real(dp) ynorm, real(dp) ans)
Performs bilinear interpolation between four points.
Performs bilinear interpolation between four points, the normalised distances from the point (1,1) are given by 'xnorm' and 'ynorm'.
Author
Mark Lomas
Date
Feb 2006
Definition at line 1023 of file data.f90.
Referenced by weather_generator::ex_clim_weather_generator(), ex_clu(), ex_soil(), crops::read_fertilizers(), crops::read_irrigation(), and weather_generator::read_wg_file().
ex_clim()
subroutine data::ex_clim (real(dp) lat, real(dp) lon, real(dp) xlatf, real(dp) xlatres, integer xlatresn, real(dp) xlon0, real(dp) xlonres, integer xlonresn, integer yr0, integer yrf, real(dp), dimension(300,12,31) tmpv, real(dp), dimension(300,12,31) humv, real(dp), dimension(300,12,31) prcv, integer isite, integer year0, integer yearf, integer siteno, integer du, integer read_par)
Extract climate data from the climate database for the nearest site.
Author
Mark Lomas
Date
Feb 2006
! Extract climate data from the climate database for the nearest site to lat,lon, replace lat,lon with the nearest cell from the database.
       UNIX                DOS
       ii(4)               ii(5)   for beginning of binary file
                                   records
       recl = 728          recl = 730     for binary climate
       recl = 577          recl = 578     for text map
Author
Mark Lomas
Date
Feb 2006
Definition at line 53 of file data.f90.
Referenced by sdgvm1::read_climate().
ex_clim_site()
subroutine data::ex_clim_site (integer yr0, integer yrf, real(dp), dimension(300,12,31) tmpv, real(dp), dimension(300,12,31) humv, real(dp), dimension(300,12,31) prcv, integer year0, integer yearf)
Extract climate data from the climate database for the nearest site.
Extract climate data from the climate database for the nearest site to lat,lon, replace lat,lon with the nearest cell from the database.
       UNIX                DOS
       ii(4)               ii(5)   for beginning of binary file
                                   records
       recl = 728          recl = 730     for binary climate
       recl = 577          recl = 578     for text map
Author
Mark Lomas
Date
Feb 2006
Definition at line 189 of file data.f90.
References func::no_days().
Referenced by sdgvm1::read_climate().
ex_clu()
subroutine data::ex_clu (real(dp) lat, real(dp) lon, integer nft, real(dp), dimension(255,100) lutab, real(dp), dimension(max_cohorts,max_years) cluse, integer yr0, integer yrf, integer du, logical l_lu)
Extract land use from land use database for the nearest site to lat,lon, replace lat,lon with the nearest cell from the database. The data contains the percent (in byte format) for each pft from 2 to nft. First reads the readme.dat from the land use dataset with info such as resolution,years available and number of classes.Description of classes and proportion assigned to model ft are ignored. Land use must be written per class per year in vector format (i3) 0-100 with 255 for water.Direction is West to East,North to South. lutab(landcover classes,nft) is read from setup file.
Author
Mark Lomas
Date
Feb 2006
Definition at line 636 of file data.f90.
References bi_lin(), func::blank(), func::in2st(), func::n_fields(), func::st2arr(), func::stcmp(), and func::stripb().
Referenced by sdgvm1::read_landuse().
ex_lu()
subroutine data::ex_lu (real(dp) lat, real(dp) lon, integer, dimension(max_years) luse, integer yr0, integer yrf, integer du)
Extract land use.
Extract land use from land use soils database for the nearest site to lat,lon, replace lat,lon with the nearest cell from the database.
Author
Mark Lomas
Date
Feb 2006
Definition at line 481 of file data.f90.
References func::n_fields(), and func::st2arr().
Referenced by sdgvm1::read_landuse().
ex_soil()
subroutine data::ex_soil (real(dp) lat, real(dp) lon, real(dp), dimension(10) sol_chr2, integer du, logical, dimension(20) l_soil)
Extract % sand % silt bulk density and depth from soils database.
Extract % sand % silt bulk density and depth from soils database.
Author
Mark Lomas
Date
Feb 2006
Definition at line 240 of file data.f90.
References bi_lin().
Referenced by sdgvm1::read_soil().
landuse1()
subroutine data::landuse1 (integer, dimension(max_years) luse, integer yr0, integer yrf, logical, dimension(max_years) fire_ant, logical, dimension(max_years) harvest_ant)
Author
Mark Lomas
Date
Feb 2006
Definition at line 1163 of file data.f90.
lorc()
subroutine data::lorc (integer du, real(dp) lat, real(dp) lon, real(dp) latdel, real(dp) londel, logical xx)
Determine if the site is a land site.
Using a half an arc-second land sea mask. Determine whether the site is land or sea based on the majority of the mask within the limits of the gridcell.
Author
Mark Lomas
Date
Feb 2006
Definition at line 842 of file data.f90.
References base72i().
Referenced by sdgvm1::land_site_check().
n7()
integer function data::n7 (integer, dimension(7) x)
Author
Mark Lomas
Date
Feb 2006
Definition at line 993 of file data.f90.
readco2()
subroutine data::readco2 (integer yr0, integer yrf, real(dp), dimension(max_years) co2, integer daily_co2, integer nyears)
Reads co2 values for each year.
It will read from the co2 file the concentration vector with starting and end year as produced by the read_input_file sub. If the co2 file has only one value then it will be used for all the years meaning constant co2 concentrations.
Author
Mark Lomas
Date
Feb 2006
Definition at line 1110 of file data.f90.