SDGVM Update Project: site_parameters Module Reference
site_parameters Module Reference
Data Types
type siteparameters
Variables
type(siteparameters), public ssp
Variable Documentation
ssp
type (siteparameters), public site_parameters::ssp
Definition at line 67 of file site_parameters.f90.
Referenced by state_methods::accumulate_burnt_soil_res(), state_methods::accumulate_dist_soil_res(), veg_dynamics::addbio(), phenology_methods::allocation(), productivity_luna_methods::assj3(), productivity_luna_methods::assj4(), productivity_luna_methods::assvmax3(), veg_dynamics::barerec(), state_methods::combine_cohorts(), state_methods::compress_state(), veg_dynamics::cover(), crops::crop_outputs(), doly::dolyday(), doly::evapotranspiration(), state_methods::ft_cover(), crops::getwet(), veg_dynamics::grassrec(), veg_dynamics::growth(), crops::harv(), hydrology_methods::hydrology(), veg_dynamics::initialise_new_cohorts(), state_methods::initialise_state(), phenology_methods::lai_add(), phenology_methods::lai_dist(), state_methods::make_co2ftmap(), veg_dynamics::mklit(), veg_dynamics::newgrowth(), productivity_methods::nppcalc(), phenology_methods::phenology(), phenology_methods::phenology1(), phenology_methods::phenology2(), phenology_methods::phenology3(), read_input::process_input_file(), state_methods::remove_cohort(), state_methods::reset_soil_res(), state_methods::restrict_cohort_numbers(), phenology_methods::root_add(), phenology_methods::root_dist(), crops::seasonality(), state_methods::set_misc_values(), state_methods::set_new_soil_res(), state_methods::set_new_soil_res2(), phenology_methods::stem_add(), phenology_methods::stem_dist(), state_methods::sum_carbon(), phenology_methods::suma_add(), crops::summerday(), veg_dynamics::thin(), and crops::winterday().