SDGVM Update Project: sdgvm1 Module Reference
sdgvm1 Module Reference
Functions/Subroutines
real(dp) function outputs (daily_out, ind, st1)
Compute outputs from daily_out.
subroutine set_landuse (ftprop, tmp, prc, nat_map, nft, cluse, year, yr0)
Set landuse by allocating the cover of new ground.
subroutine set_climate (xtmpv, xprcv, xhumv, xcldv, xswrv, withcloudcover, yearv, iyear, tmp, prc, hum, cld, swr, thty_dys, yr0, year, nyears, nn1)
Set 'tmp' 'hum' 'prc' and 'cld'.
subroutine set_co2 (ca, iyear, speedc, co2, year, yr0)
Set CO2 value 'ca'.
subroutine read_landuse (ilanduse, yr0, yrf, du, nft, lat, lon, lutab, luse, cluse, l_lu)
subroutine read_climate (lat, lon, xlatf, xlatres, xlatresn, xlon0, xlonres, xlonresn, yr0, yrf, xtmpv, xhumv, xprcv, xcldv, xswrv, isite, xyear0, xyearf, du, seed1, seed2, seed3, l_clim, l_stats, siteno, day_mnth, thty_dys, sit_grd, withcloudcover)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine get_input_filename (st1)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine country (lat, lon, country_name, country_id, l_regional)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine co2_0_f (co20, co2f, yearv, yr0, co2, nyears)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine read_soil (lat, lon, soil_chr, soil_chr2, du, l_soil)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine land_site_check (st1, sites, lat_lon, latdel, londel, du)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine output_options (nomdos, otags, omav, ofmt_daily, ofmt_monthly, ofmt_yearly)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine set_pixel_out (st1, st2, outyears, nomdos, otagsn, otags, oymd)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine set_subpixel_out (st1, st2, outyears, nomdos, otagsnft, otags, oymdft, out_cov, out_bio, out_bud, out_sen)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine mkdlit ()
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine sum_soilcn (soilc, soiln, minn)
sum_soilcn
subroutine swap (ic0, in0, iminn, c0, n0, minn)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
subroutine mix_water (ftcov, nft)
Function/Subroutine Documentation
co2_0_f()
subroutine sdgvm1::co2_0_f (real(dp) co20, real(dp) co2f, integer, dimension(max_years) yearv, integer yr0, real(dp), dimension(max_years) co2, integer nyears)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 639 of file sdgvm1.f90.
Referenced by sdgvm().
country()
subroutine sdgvm1::country (real(dp) lat, real(dp) lon, character(len=str_len) country_name, integer country_id, logical l_regional)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 454 of file sdgvm1.f90.
Referenced by sdgvm().
get_input_filename()
subroutine sdgvm1::get_input_filename (character st1)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 420 of file sdgvm1.f90.
Referenced by sdgvm().
land_site_check()
subroutine sdgvm1::land_site_check (character(len=str_len) st1, integer sites, real(dp), dimension(max_sites,2) lat_lon, real(dp) latdel, real(dp) londel, integer du)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 764 of file sdgvm1.f90.
References file_object::fun, and data::lorc().
Referenced by read_input::process_input_file().
mix_water()
subroutine sdgvm1::mix_water (real(dp), dimension(max_cohorts) ftcov, integer nft)
Author
Mark Lomas
Date
Feb 2006
Parameters
ftcov Holds total cover for each ft
Definition at line 1330 of file sdgvm1.f90.
mkdlit()
subroutine sdgvm1::mkdlit ()
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 1220 of file sdgvm1.f90.
Referenced by sdgvm().
output_options()
subroutine sdgvm1::output_options (integer nomdos, character(len=str_len), dimension(max_outputs) otags, integer, dimension(max_outputs) omav, character(len=str_len), dimension(max_outputs) ofmt_daily, character(len=str_len), dimension(max_outputs) ofmt_monthly, character(len=str_len), dimension(max_outputs) ofmt_yearly)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 817 of file sdgvm1.f90.
Referenced by read_input::process_input_file().
outputs()
real(dp) function sdgvm1::outputs (real(dp), dimension(max_outputs,max_cohorts,12,31) daily_out, integer ind, character(len=3) st1)
Compute outputs from daily_out.
Four forms of outputs are available and are specified by 'st1' which can take any one of the values ['Add', 'Average', 'Max', 'Min'].
Author
Mark Lomas
Date
Feb 2006
Definition at line 33 of file sdgvm1.f90.
Referenced by sdgvm().
read_climate()
subroutine sdgvm1::read_climate (real(dp) lat, real(dp) lon, real(dp) xlatf, real(dp) xlatres, integer xlatresn, real(dp) xlon0, real(dp) xlonres, integer xlonresn, integer yr0, integer yrf, real(dp), dimension(500,12,31) xtmpv, real(dp), dimension(500,12,31) xhumv, real(dp), dimension(500,12,31) xprcv, real(dp), dimension(500,12) xcldv, real(dp), dimension(500,12,31) xswrv, integer isite, integer xyear0, integer xyearf, integer du, integer seed1, integer seed2, integer seed3, logical l_clim, logical l_stats, integer siteno, integer day_mnth, integer thty_dys, integer sit_grd, logical withcloudcover)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 365 of file sdgvm1.f90.
References data::ex_clim(), data::ex_clim_site(), and weather_generator::ex_clim_weather_generator().
Referenced by sdgvm().
read_landuse()
subroutine sdgvm1::read_landuse (integer ilanduse, integer yr0, integer yrf, integer du, integer nft, real(dp) lat, real(dp) lon, real(dp), dimension(255,100) lutab, integer, dimension(max_years) luse, real(dp), dimension(max_cohorts,max_years) cluse, logical l_lu)
Author
Mark Lomas
Date
Feb 2006
Definition at line 279 of file sdgvm1.f90.
References data::ex_clu(), data::ex_lu(), and func::ntags().
Referenced by sdgvm().
read_soil()
subroutine sdgvm1::read_soil (real(dp) lat, real(dp) lon, real(dp), dimension(10) soil_chr, real(dp), dimension(10) soil_chr2, integer du, logical, dimension(20) l_soil)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 690 of file sdgvm1.f90.
References data::ex_soil().
Referenced by sdgvm().
set_climate()
subroutine sdgvm1::set_climate (real(dp), dimension(500,12,31) xtmpv, real(dp), dimension(500,12,31) xprcv, real(dp), dimension(500,12,31) xhumv, real(dp), dimension(500,12) xcldv, real(dp), dimension(500,12,31) xswrv, logical withcloudcover, integer, dimension(max_years) yearv, integer iyear, real(dp), dimension(12,31) tmp, real(dp), dimension(12,31) prc, real(dp), dimension(12,31) hum, real(dp), dimension(12) cld, real(dp), dimension(12,31) swr, integer thty_dys, integer yr0, integer year, integer nyears, integer nn1)
Set 'tmp' 'hum' 'prc' and 'cld'.
Assign climate from the raw data which is help in 'x???v' arrays. It also calculates the monthly average of temperature,precipitation and humidity.It uses that info to calculate the exponentially-weighted 20-year monthly means which are assigned to site structure variable ssp.Those values are required for the crop processes. Note that here I want to calculate the 20-year monthly mean twice,one for this year and one for the next which is the reason why this sub is in a loop.Careful,the index nn1 that goes from the loop in the sub goes from 1 to 0.
Author
Mark Lomas,EPK
Date
Oct 2016
Definition at line 168 of file sdgvm1.f90.
References func::no_days().
Referenced by sdgvm().
set_co2()
subroutine sdgvm1::set_co2 (real(dp) ca, integer iyear, logical speedc, real(dp), dimension(max_years) co2, integer year, integer yr0)
Set CO2 value 'ca'.
Author
Mark Lomas
Date
Feb 2006
Definition at line 240 of file sdgvm1.f90.
Referenced by sdgvm().
set_landuse()
subroutine sdgvm1::set_landuse (real(dp), dimension(max_cohorts) ftprop, real(dp), dimension(12,31) tmp, real(dp), dimension(12,31) prc, integer, dimension(8) nat_map, integer nft, real(dp), dimension(max_cohorts,max_years) cluse, integer year, integer yr0)
Set landuse by allocating the cover of new ground.
Assign gound available for new growth, through disturbance and mortality, given by ftprop. For the specific year,check whether each ft can grow. If it can then ftprop(ft) acquires the value of cluse array which holds the desired cover for each ft and year as read from cover file. If ftprop(1)<0 then it sets it to 0 and proportionally reduced the cover of the ofther fts to add up to 100.
Author
Mark Lomas
Date
Feb 2006
Definition at line 114 of file sdgvm1.f90.
References func::check_ft_grow().
Referenced by sdgvm().
set_pixel_out()
subroutine sdgvm1::set_pixel_out (character(len=str_len) st1, character(len=str_len) st2, integer outyears, integer nomdos, integer, dimension(max_outputs) otagsn, character(len=str_len), dimension(max_outputs) otags, integer oymd)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 991 of file sdgvm1.f90.
References func::blank(), func::n_fields(), func::ntags(), func::stcmp(), func::stripb(), func::stripbn(), and func::stripbs().
Referenced by read_input::process_input_file().
set_subpixel_out()
subroutine sdgvm1::set_subpixel_out (character(len=str_len) st1, character(len=str_len) st2, integer outyears, integer nomdos, integer, dimension(max_outputs) otagsnft, character(len=str_len), dimension(max_outputs) otags, integer oymdft, logical out_cov, logical out_bio, logical out_bud, logical out_sen)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 1092 of file sdgvm1.f90.
References func::blank(), func::n_fields(), func::ntags(), func::stcmp(), func::stripb(), func::stripbn(), and func::stripbs().
Referenced by read_input::process_input_file().
sum_soilcn()
subroutine sdgvm1::sum_soilcn (real(dp), dimension(max_cohorts) soilc, real(dp), dimension(max_cohorts) soiln, real(dp), dimension(max_cohorts) minn)
sum_soilcn
! Adds up carbon and nitrogen in the soil for each cohorts
Author
Mark Lomas
Date
Feb 2006
Definition at line 1259 of file sdgvm1.f90.
Referenced by sdgvm().
swap()
subroutine sdgvm1::swap (real(dp), dimension(8) ic0, real(dp), dimension(8) in0, real(dp), dimension(3) iminn, real(dp), dimension(8) c0, real(dp), dimension(8) n0, real(dp), dimension(3) minn)
Read internal parameters from "param.dat" file, and io parameters from "misc_params.dat".
Author
Mark Lomas
Date
Feb 2006
Definition at line 1297 of file sdgvm1.f90.