SDGVM Update Project: pft_parameters Module Reference
pft_parameters Module Reference
Data Types
type pftparameters
Variables
type(pftparameters), dimension(max_cohorts), public pft
type(pftparameters), dimension(max_pfts), public pft_tab
Variable Documentation
pft
type (pftparameters), dimension(max_cohorts), public pft_parameters::pft
Definition at line 66 of file pft_parameters.f90.
Referenced by state_methods::accumulate_burnt_soil_res(), state_methods::accumulate_dist_soil_res(), phenology_methods::allocation(), productivity_luna_methods::assj3(), productivity_luna_methods::assvmax3(), func::check_ft_grow(), state_methods::compress_state(), state_methods::ft_cover(), crops::harv(), hydrology_methods::hydrology(), state_methods::initialise_state(), state_methods::initialise_state_cohort(), crops::irrigate(), phenology_methods::lai_add(), phenology_methods::lai_dist(), state_methods::make_co2ftmap(), productivity_methods::nppcalc(), phenology_methods::phenology(), phenology_methods::phenology1(), phenology_methods::phenology2(), phenology_methods::phenology3(), state_methods::remove_cohort(), state_methods::restrict_cohort_numbers(), phenology_methods::root_add(), sdgvm(), phenology_methods::stem_add(), and state_methods::sum_carbon().
pft_tab
type (pftparameters), dimension(max_pfts), public pft_parameters::pft_tab
Definition at line 66 of file pft_parameters.f90.
Referenced by func::check_ft_grow(), crops::crop_outputs(), crops::fert_crops(), state_methods::initialise_state(), state_methods::make_co2ftmap(), open_files::open_optional(), open_files::open_site_info(), open_files::open_tile_pft(), read_input::process_input_file(), crops::read_opt_par(), sdgvm(), and crops::seasonality().