SDGVM Update Project: crops Module Reference
crops Module Reference
Crop subroutines.
Functions/Subroutines
subroutine seasonality (tmp, prc, cld, thty_dys, nft, year, nn1)
Crops Seasonality.
subroutine getwet (hrs, q, wet, pet, nn1)
integer function summerday (thresh, mmid, nn1)
Find the start day of summer as defined by a threshold temperature.
integer function winterday (thresh, mmid, nn1)
Find the start day of winter as defined by a threshold temperature.
subroutine wangengel (tmin, topt, tmax, tmp, dtype, popt, pcrit, p, ft, fp)
Get temperature and photoperiod response function values for crops.
subroutine streck (vtmin, vtopt, vtmax, tmp, dtype, popt, pcrit, p, vdays, fv)
Get vernalisation factors for crops.
subroutine crop_outputs (nft, sl)
Output files for crops.
subroutine irrigate (ft, sfc, sw)
Decides irrigation and fills up relative soil layers.
subroutine fert_crops (nft)
Effect of fertilizer usage on optimal crop LAI.
subroutine read_fertilizers (du, yr0, yrf, lat, lon, nft, cfert)
subroutine read_irrigation (du, yr0, yrf, lat, lon, nft, cirr)
subroutine harv (lit, yielit)
Harvest of crops.
subroutine read_opt_par ()
Detailed Description
Crop subroutines.
Author
Date
Function/Subroutine Documentation
crop_outputs()
subroutine crops::crop_outputs (integer nft, integer sl)
Output files for crops.
Author
EPK
Date
Dec 2016
Definition at line 647 of file crops.f90.
References pft_parameters::pft_tab, site_parameters::ssp, and system_state::ssv.
fert_crops()
subroutine crops::fert_crops (integer nft)
Effect of fertilizer usage on optimal crop LAI.
Author
LLT,EPK
Date
Jan 2017
Definition at line 825 of file crops.f90.
References pft_parameters::pft_tab.
Referenced by sdgvm().
getwet()
subroutine crops::getwet (real(dp), dimension(12) hrs, real(dp), dimension(12) q, integer wet, real(dp), dimension(12) pet, integer nn1)
Calculate ratios of precipitation to evt van Bussel (2011) discusses determination of start of growing period in her chapter 5, section 2.2.2, and the sowing day should be the first day where precip>0.1mm of that wet month. Calculate 4-month sums of prec/evt (petsum(12) and find the highest. Output the starting month of the highest (wet). We depart from van Bussel in that we do not use Priestley-Taylor PET, but instead lift Penman-Montheith code from of dolyday.
REFERENCES:
Waha et al 2012, Global Ecology and Biogeography 21:247-259 van Bussel et al 2015, Global Ecology and Biogeography (earlyview)
hrs(12) IN Daylight hours for the midday of each month q(12) IN Monthly photon flux density wet OUT Month index for start of wet season pet(12) OUT Monthly ratio precip/(potential evapotranspiration)
Author
LLT,EPK
Date
Oct 2016
Definition at line 358 of file crops.f90.
References site_parameters::ssp.
Referenced by seasonality().
harv()
subroutine crops::harv (real(dp) lit, real(dp) yielit)
Harvest of crops.
Author
EPK
Date
Mar 2017
Definition at line 1193 of file crops.f90.
References pft_parameters::pft, site_parameters::ssp, and system_state::ssv.
Referenced by phenology_methods::allocation().
irrigate()
subroutine crops::irrigate (integer ft, real(dp), dimension(4) sfc, real(dp), dimension(4) sw)
Decides irrigation and fills up relative soil layers.
sfc is soil field capacity in mm sw is soil wilting point in mm ssv(ft)soil_h2o is soil water content in mm We should also consider runoff.Ideally,we would check runoff before irrigating as it would give us the water available for irrigation. We would then subtract the water used for irrigation from runoff.
Author
LLT,EPK
Date
Jan 2017
Definition at line 749 of file crops.f90.
References pft_parameters::pft, and system_state::ssv.
Referenced by sdgvm().
read_fertilizers()
subroutine crops::read_fertilizers (integer du, integer yr0, integer yrf, real(dp) lat, real(dp) lon, integer nft, real(dp), dimension(max_cohorts,max_years,3) cfert)
Author
EPK
Date
Feb 2017
Definition at line 867 of file crops.f90.
References data::bi_lin(), func::blank(), func::in2st(), func::n_fields(), func::st2arr(), func::stcmp(), and func::stripb().
Referenced by sdgvm().
read_irrigation()
subroutine crops::read_irrigation (integer du, integer yr0, integer yrf, real(dp) lat, real(dp) lon, integer nft, real(dp), dimension(max_cohorts,max_years) cirr)
Author
EPK
Date
Feb 2017
Definition at line 1036 of file crops.f90.
References data::bi_lin(), func::blank(), func::in2st(), func::n_fields(), func::st2arr(), func::stcmp(), and func::stripb().
Referenced by sdgvm().
read_opt_par()
subroutine crops::read_opt_par ()
Author
EPK
Date
MAR 2017
Definition at line 1294 of file crops.f90.
References pft_parameters::pft_tab.
seasonality()
subroutine crops::seasonality (real(dp), dimension(12,31) tmp, real(dp), dimension(12,31) prc, real(dp), dimension(12) cld, integer thty_dys, integer nft, integer year, integer nn1)
Crops Seasonality.
Following Waha et al 2012 (published version of LGJ van Bussel's thesis (2011) chapter 5), calculate variation coefficients for seasonality, which may control sowing dates. Then, get the sowing day based on precipitation or summer/winter temperature thresholds for each crop.
Definition at line 58 of file crops.f90.
References light_methods::dayl(), getwet(), func::no_days(), light_methods::pfd(), pft_parameters::pft_tab, site_parameters::ssp, streck(), summerday(), wangengel(), and winterday().
Referenced by sdgvm().
streck()
subroutine crops::streck (real(dp) vtmin, real(dp) vtopt, real(dp) vtmax, real(dp) tmp, real(dp) dtype, real(dp) popt, real(dp) pcrit, real(dp) p, real(dp) vdays, real(dp) fv)
Get vernalisation factors for crops.
Following Streck et al 2003, Ag For Meteor 115:139-150 Equations 3 and 4 (temperature function), 5 (photoperiod function) These functions are from Wang and Engel 1998 (Agri Sys 58:1-24). In some papers including Streck et al's first one (below) the temperature function has a typographical error (a minus sign is missing). The sum of the product of the temperature and photoperiod functions gives the effective vernalised days VD which one can use to get the vernalization response function (Eq 10) or Eq 2 in Streck et al 2003 Agron J 95:155-159
Streck et al's vernalisation function and Wang and Engel's functions are used in a number of models:
JULES-SUCROS land surface model (van den Hoof et al 2011 Ag For Meteor 151:137-153) DANUBIA crop growth model (Lenz-Wiedemann et al 2010 Ecol Model 221:314-329) FROSTOL wheat model (Bergjord et al 2008 Eur J Agr 28:321-330) SPACSYS C and N cycling model (Bingham and Wu 2011 Eur J Agr 34:181-189) CANDY-PLUS C, N and biomass model (Kruger et al 2013 Vadose Zone J 12) Liu's pasture legume model (Liu 2007 Field Crops Res 101:331-342)
vtmin,vtopt,vtmax input Cardinal temperatures for vernalisation tmp input Current mean daily temperature popt,pcrit input Optimal and critical photoperiod p input Current photoperiod dtype input -1: short-day, 1: long-day, 0: day-neutral vdays input/output Accumulated vernalisation days fv output Current vernalisation day
Author
LLT,EPK
Date
Oct 2016
Definition at line 604 of file crops.f90.
References wangengel().
Referenced by phenology_methods::phenology3(), and seasonality().
summerday()
integer function crops::summerday (real(dp) thresh, integer, dimension(12) mmid, integer nn1)
Find the start day of summer as defined by a threshold temperature.
van Bussel (2011, thesis) discusses determination of sowing dates in her chapter 5, section 2.2.2; here we find the day number when summer begins (temperature>=threshold). We linearly interpolate between the average monthly temperatures to get the mean day.
thresh IN threshold temperature for summer mmid(12) IN Midday of month in Julian days
Author
LLT,EPK
Date
Oct 2016
Definition at line 439 of file crops.f90.
References site_parameters::ssp.
Referenced by seasonality().
wangengel()
subroutine crops::wangengel (real(dp) tmin, real(dp) topt, real(dp) tmax, real(dp) tmp, real(dp) dtype, real(dp) popt, real(dp) pcrit, real(dp) p, real(dp) ft, real(dp) fp)
Get temperature and photoperiod response function values for crops.
These functions are from Wang and Engel 1998 (Agri Sys 58:1-24). The sum of the product of the temperature and photoperiod functions gives the effective physiological days.
Author
LLT,EPK
Date
Oct 2016
Definition at line 529 of file crops.f90.
Referenced by phenology_methods::phenology3(), seasonality(), and streck().
winterday()
integer function crops::winterday (real(dp) thresh, integer, dimension(12) mmid, integer nn1)
Find the start day of winter as defined by a threshold temperature.
thresh IN threshold temperature for winter mmid(12) IN Midday of month in Julian days
Author
LLT,EPK
Date
Oct 2016
Definition at line 486 of file crops.f90.
References site_parameters::ssp.
Referenced by seasonality().