SDGVM Update Project: productivity_luna_methods Module Reference
productivity_luna_methods Module Reference
Functions/Subroutines
subroutine assimilation_calc (c3, t, rn, soil2g, wtwp, fshade, fsunlit, qshade, qsunlit, jshade, jsunlit, canga, tk, p, rlai, rh, oi, ca, vmx, kg, ko, kc, tau, rd, ga, t154, xdvy, dv, px, oitau1, oitau2, gsmin, kcoiko, upt, a, ci, gs, gs_type, ii)
subroutine assj3 (a, ci, gs, oi, ca, rh, kg, tau, rd, ga, t, p, j, t154, xdvy, dv, px, oitau1, oitau2, gsmin, gs_type, ii)
real(dp) function t_scalar (t, jv, ttype, ftTopt, ftkHa, ftkHd, tmonth, jfv)
subroutine assvmax3 (a, ci, cs, gs, oi, ca, vmx, rh, kg, ko, kc, tau, rd, ga, t, p, t154, xdvy, dv, px, oitau1, oitau2, kcoiko, gsmin, gs_type, ii)
real(dp) function gs_calc (g0, g1, t, kg, a, cs, dv, t154, gs_type)
subroutine assvmax (a, ci, cs, gs, oi, ca, vmx, rh, kg, ko, kc, tau, rd, ga, t, p, gsmin, gs_type)
subroutine assj4 (a, ci, gs, oi, ca, rh, kg, tau, rd, ga, t, p, j, t154, xdvy, dv, px, oitau1, oitau2, gsmin, gs_type, ii)
subroutine assj (a, ci, gs, oi, ca, rh, kg, tau, rd, ga, t, p, j, gs_type)
subroutine limitationprocess (av, pcv, gsv, aj, pcj, gsj, a, pc, gs)
subroutine assc4 (a, pc, gs, pa, vmax, rh, t, qg, p, up)
real(dp) function max_daily_pchg (tleaf10)
Function/Subroutine Documentation
assc4()
subroutine productivity_luna_methods::assc4 (real(dp) a, real(dp) pc, real(dp) gs, real(dp) pa, real(dp) vmax, real(dp) rh, real(dp) t, real(dp) qg, real(dp) p, real(dp) up)
Definition at line 661 of file productivity_luna_methods.f90.
Referenced by assimilation_calc().
assimilation_calc()
subroutine productivity_luna_methods::assimilation_calc (integer c3, real(dp) t, real(dp) rn, real(dp) soil2g, real(dp) wtwp, real(dp) fshade, real(dp) fsunlit, real(dp) qshade, real(dp) qsunlit, real(dp) jshade, real(dp) jsunlit, real(dp) canga, real(dp) tk, real(dp) p, real(dp) rlai, real(dp) rh, real(dp) oi, real(dp) ca, real(dp) vmx, real(dp) kg, real(dp) ko, real(dp) kc, real(dp) tau, real(dp) rd, real(dp) ga, real(dp) t154, real(dp) xdvy, real(dp) dv, real(dp) px, real(dp) oitau1, real(dp) oitau2, real(dp) gsmin, real(dp) kcoiko, real(dp) upt, real(dp) a, real(dp) ci, real(dp) gs, integer gs_type, integer ii)
Definition at line 23 of file productivity_luna_methods.f90.
References assc4(), assj3(), assj4(), assvmax3(), and limitationprocess().
Referenced by productivity_methods::nppcalc().
assj()
subroutine productivity_luna_methods::assj (real(dp) a, real(dp) ci, real(dp) gs, real(dp) oi, real(dp) ca, real(dp) rh, real(dp) kg, real(dp) tau, real(dp) rd, real(dp) ga, real(dp) t, real(dp) p, real(dp) j, integer gs_type)
Definition at line 509 of file productivity_luna_methods.f90.
References gs_calc().
Referenced by assj3(), and assj4().
assj3()
subroutine productivity_luna_methods::assj3 (real(dp) a, real(dp) ci, real(dp) gs, real(dp) oi, real(dp) ca, real(dp) rh, real(dp) kg, real(dp) tau, real(dp) rd, real(dp) ga, real(dp) t, real(dp) p, real(dp) j, real(dp) t154, real(dp) xdvy, real(dp) dv, real(dp) px, real(dp) oitau1, real(dp) oitau2, real(dp) gsmin, integer gs_type, integer ii)
Definition at line 144 of file productivity_luna_methods.f90.
References assj(), gs_calc(), pft_parameters::pft, site_parameters::ssp, and system_state::ssv.
Referenced by assimilation_calc().
assj4()
subroutine productivity_luna_methods::assj4 (real(dp) a, real(dp) ci, real(dp) gs, real(dp) oi, real(dp) ca, real(dp) rh, real(dp) kg, real(dp) tau, real(dp) rd, real(dp) ga, real(dp) t, real(dp) p, real(dp) j, real(dp) t154, real(dp) xdvy, real(dp) dv, real(dp) px, real(dp) oitau1, real(dp) oitau2, real(dp) gsmin, integer gs_type, integer ii)
Definition at line 466 of file productivity_luna_methods.f90.
References assj(), gs_calc(), site_parameters::ssp, and system_state::ssv.
Referenced by assimilation_calc().
assvmax()
subroutine productivity_luna_methods::assvmax (real(dp) a, real(dp) ci, real(dp) cs, real(dp) gs, real(dp) oi, real(dp) ca, real(dp) vmx, real(dp) rh, real(dp) kg, real(dp) ko, real(dp) kc, real(dp) tau, real(dp) rd, real(dp) ga, real(dp) t, real(dp) p, real(dp) gsmin, integer gs_type)
Definition at line 361 of file productivity_luna_methods.f90.
References gs_calc().
Referenced by assvmax3().
assvmax3()
subroutine productivity_luna_methods::assvmax3 (real(dp) a, real(dp) ci, real(dp) cs, real(dp) gs, real(dp) oi, real(dp) ca, real(dp) vmx, real(dp) rh, real(dp) kg, real(dp) ko, real(dp) kc, real(dp) tau, real(dp) rd, real(dp) ga, real(dp) t, real(dp) p, real(dp) t154, real(dp) xdvy, real(dp) dv, real(dp) px, real(dp) oitau1, real(dp) oitau2, real(dp) kcoiko, real(dp) gsmin, integer gs_type, integer ii)
Definition at line 260 of file productivity_luna_methods.f90.
References assvmax(), gs_calc(), pft_parameters::pft, site_parameters::ssp, and system_state::ssv.
Referenced by assimilation_calc().
gs_calc()
real(dp) function productivity_luna_methods::gs_calc (real(dp) g0, real(dp) g1, real(dp) t, real(dp) kg, real(dp) a, real(dp) cs, real(dp) dv, real(dp) t154, integer gs_type)
Definition at line 297 of file productivity_luna_methods.f90.
Referenced by assj(), assj3(), assj4(), assvmax(), and assvmax3().
limitationprocess()
subroutine productivity_luna_methods::limitationprocess (real(dp) av, real(dp) pcv, real(dp) gsv, real(dp) aj, real(dp) pcj, real(dp) gsj, real(dp) a, real(dp) pc, real(dp) gs)
Definition at line 615 of file productivity_luna_methods.f90.
Referenced by assimilation_calc().
max_daily_pchg()
real(dp) function productivity_luna_methods::max_daily_pchg (real(dp), intent(in) tleaf10)
Definition at line 709 of file productivity_luna_methods.f90.
Referenced by productivity_methods::nppcalc().
t_scalar()
real(dp) function productivity_luna_methods::t_scalar (real(dp) t, character jv, integer, intent(in) ttype, real(dp) ftTopt, real(dp) ftkHa, real(dp) ftkHd, real(dp) tmonth, logical, intent(in) jfv)
Definition at line 178 of file productivity_luna_methods.f90.
Referenced by productivity_methods::brent_solver(), luna_methods::luna(), productivity_methods::nppcalc(), and luna_methods::nue().