SDGVM Update Project: productivity_methods Module Reference
productivity_methods Module Reference
Functions/Subroutines
subroutine nppcalc (npp_eff, c3, maxc, soilc, soiln, minn, soil2g, wtwp, wtfc, rd, rlai, t, rh, ca, oi, rn, qdirect, qdiff, can2a, can2g, canres, suma, amx, amax, gsum, hrs, canga, p, nleaf_sum, fpr, tleaf_n, tleaf_p, ce_light, ce_ci, ce_t, ce_maxlight, ce_ga, ce_rh, ft, par_loops, cld, lat, year, mnth, day, thty_dys, gs_type, swr)
subroutine assj2 (a, w, pc, gs, po, pa, j, g0, g1, rh, kg, tau, rd, acheck)
subroutine xamax (a, xt, oi, vmx, rd, j, dresp, pc)
subroutine assc42 (a, w, pc, gs, po, pa, vmax, g0, g1, rh, kg, tau, rd, t, qg, acheck, up)
subroutine xvjmax (vmx, jmx, j, xt, xq, sum, nup, oi, dresp)
subroutine jcalc (q, jmx, fw1984, j)
real(dp) function brent_solver (func, i1, i2, oi, ca, vmx, j, rh, kg, rd, ga, t, p, gs_func, g0, g1, dv, i, ci, light, ttype, ftToptV, ftHaV, ftHdV, ftToptJ, ftHaJ, ftHdJ, tmonth, jfv)
real(dp) function vcmax_maire (vm, vt, jt, ci, km, gstar, alpha, light, farq_pars_func, i)
subroutine farq_pars (t, kc, ko, tau, alpha, farq_pars_func)
Function/Subroutine Documentation
assc42()
subroutine productivity_methods::assc42 (real(dp) a, real(dp) w, real(dp) pc, real(dp) gs, real(dp) po, real(dp) pa, real(dp) vmax, real(dp) g0, real(dp) g1, real(dp) rh, real(dp) kg, real(dp) tau, real(dp) rd, real(dp) t, real(dp) qg, real(dp) acheck, real(dp) up)
Definition at line 1039 of file productivity_methods.f90.
assj2()
subroutine productivity_methods::assj2 (real(dp) a, real(dp) w, real(dp) pc, real(dp) gs, real(dp) po, real(dp) pa, real(dp) j, real(dp) g0, real(dp) g1, real(dp) rh, real(dp) kg, real(dp) tau, real(dp) rd, real(dp) acheck)
Definition at line 881 of file productivity_methods.f90.
brent_solver()
real(dp) function productivity_methods::brent_solver (integer func, real(dp) i1, real(dp) i2, real(dp) oi, real(dp) ca, real(dp) vmx, real(dp) j, real(dp) rh, real(dp) kg, real(dp) rd, real(dp) ga, real(dp) t, real(dp) p, integer gs_func, real(dp) g0, real(dp) g1, real(dp) dv, integer i, real(dp) ci, real(dp) light, integer ttype, real(dp) ftToptV, real(dp) ftHaV, real(dp) ftHdV, real(dp) ftToptJ, real(dp) ftHaJ, real(dp) ftHdJ, real(dp) tmonth, logical jfv)
Definition at line 1311 of file productivity_methods.f90.
References farq_pars(), productivity_luna_methods::t_scalar(), and vcmax_maire().
Referenced by nppcalc().
farq_pars()
subroutine productivity_methods::farq_pars (real(dp) t, real(dp) kc, real(dp) ko, real(dp) tau, real(dp) alpha, integer farq_pars_func)
Definition at line 1500 of file productivity_methods.f90.
Referenced by brent_solver().
jcalc()
subroutine productivity_methods::jcalc (real(dp) q, real(dp) jmx, logical fw1984, real(dp) j)
Definition at line 1277 of file productivity_methods.f90.
Referenced by nppcalc().
nppcalc()
subroutine productivity_methods::nppcalc (real(dp) npp_eff, integer c3, real(dp) maxc, real(dp) soilc, real(dp) soiln, real(dp) minn, real(dp) soil2g, real(dp) wtwp, real(dp) wtfc, real(dp), dimension(12) rd, real(dp) rlai, real(dp) t, real(dp) rh, real(dp) ca, real(dp) oi, real(dp) rn, real(dp) qdirect, real(dp) qdiff, real(dp) can2a, real(dp) can2g, real(dp) canres, real(dp) suma, real(dp) amx, real(dp) amax, real(dp) gsum, real(dp) hrs, real(dp) canga, real(dp) p, real(dp) nleaf_sum, real(dp) fpr, real(dp) tleaf_n, real(dp) tleaf_p, real(dp), dimension(30,12) ce_light, real(dp), dimension(30,12) ce_ci, real(dp), dimension(30) ce_t, real(dp), dimension(30,12) ce_maxlight, real(dp), dimension(30,12) ce_ga, real(dp), dimension(30) ce_rh, integer ft, integer par_loops, real(dp) cld, real(dp) lat, integer year, integer mnth, integer day, integer thty_dys, integer gs_type, real(dp) swr)
Author
Mark Lomas
Date
Feb 2006
Definition at line 40 of file productivity_methods.f90.
References productivity_luna_methods::assimilation_calc(), brent_solver(), sunshade::goudriaanslaw2(), sunshade::goudriaanslaw_ant(), jcalc(), luna_methods::luna(), luna_methods::luna_nogrowth(), productivity_luna_methods::max_daily_pchg(), func::no_day(), light_methods::pfd_ant(), pft_parameters::pft, site_parameters::ssp, productivity_luna_methods::t_scalar(), and tuning_parameters::tgp.
Referenced by doly::dolyday().
vcmax_maire()
real(dp) function productivity_methods::vcmax_maire (real(dp) vm, real(dp) vt, real(dp) jt, real(dp) ci, real(dp) km, real(dp) gstar, real(dp) alpha, real(dp) light, integer farq_pars_func, integer i)
Definition at line 1469 of file productivity_methods.f90.
Referenced by brent_solver().
xamax()
subroutine productivity_methods::xamax (real(dp) a, real(dp) xt, real(dp) oi, real(dp) vmx, real(dp) rd, real(dp) j, real(dp) dresp, real(dp) pc)
Definition at line 970 of file productivity_methods.f90.
xvjmax()
subroutine productivity_methods::xvjmax (real(dp) vmx, real(dp) jmx, real(dp) j, real(dp) xt, real(dp) xq, real(dp) sum, real(dp) nup, real(dp) oi, real(dp) dresp)
Definition at line 1198 of file productivity_methods.f90.