SDGVM Update Project: phenology_methods Module Reference
phenology_methods Module Reference
Methods which control the phenology, carbon allocation, and the aging and updating of the active carbon stem, root, leaf compartments. Along with suma which is also compartmentalised in a similar manner.
Functions/Subroutines
subroutine phenology (yield, laiinc)
subroutine phenology1 (yield, laiinc)
subroutine phenology2 (yield, laiinc)
subroutine phenology3 (yield, laiinc)
subroutine allocation (laiinc, daygpp, resp_l, lmor_sc, resp, leaflit, stemnpp, rootnpp, resp_s, resp_r, resp_m, check_closure)
Allocate GPP between storage, stems, roots and leaves.
subroutine suma_add (laiinc)
Update suma by adding daily increase and removing via mortality.
subroutine stem_add (stem_inc, stem_fixed)
Update stems by adding daily increase and removing via mortality.
subroutine root_add (laiinc, leaflit)
Update roots by adding daily increase and removing via mortality.
subroutine lai_add (laiinc, leaflit)
subroutine stem_dist (respref, resp)
Apply stem respiration to the active stems, and sum the resulting stems.
subroutine root_dist (respref, resp)
Apply root respiration to the active roots, and sum the resulting roots.
subroutine lai_dist (lmor_sc, leaflit)
(Currently not implemented). Apply leaf motality.
Detailed Description
Methods which control the phenology, carbon allocation, and the aging and updating of the active carbon stem, root, leaf compartments. Along with suma which is also compartmentalised in a similar manner.
The active carbon pools of stem root and leaf, as well as suma are compartmentalised into bins of an integral number of days long eg. 'lai_comp_length' in the 'dims' module.
Todo:
Basicly the compartments are behaving like a linked list but using more memory. More memoty efficient to use linked lists.
Compartments
Compartments are created as and when required. Each compartment is a structure containing a real variable 'val' and an integer value 'age'. The variable 'age' is set equal to the Julian day that the compartment was created, and remains constant at that value. Once created a compartment will accumulate any carbon for the following number of days given by 'var_comp_length'.
Function/Subroutine Documentation
allocation()
subroutine phenology_methods::allocation (real(dp) laiinc, real(dp) daygpp, real(dp) resp_l, real(dp), dimension(3600) lmor_sc, real(dp) resp, real(dp) leaflit, real(dp) stemnpp, real(dp) rootnpp, real(dp) resp_s, real(dp) resp_r, real(dp) resp_m, logical check_closure)
Allocate GPP between storage, stems, roots and leaves.
Author
Mark Lomas
Date
Feb 2006
Definition at line 898 of file phenology_methods.f90.
References crops::harv(), lai_add(), lai_dist(), misc_values::msv, pft_parameters::pft, root_add(), root_dist(), site_parameters::ssp, system_state::ssv, stem_add(), stem_dist(), and tuning_parameters::tgp.
Referenced by sdgvm().
lai_add()
subroutine phenology_methods::lai_add (real(dp) laiinc, real(dp) leaflit)
Author
Mark Lomas,EPK
Date
May,2017
Definition at line 1340 of file phenology_methods.f90.
References dims::lai_comp_length, pft_parameters::pft, site_parameters::ssp, and system_state::ssv.
Referenced by allocation().
lai_dist()
subroutine phenology_methods::lai_dist (real(dp), dimension(3600) lmor_sc, real(dp) leaflit)
(Currently not implemented). Apply leaf motality.
Leaf mortality is applied to the current cohort. The mortality values are taken from 'lmor_sc' and are applied to the lai compartments which span the age of the leaf.
Author
Mark Lomas
Date
Feb 2006
Definition at line 1535 of file phenology_methods.f90.
References pft_parameters::pft, site_parameters::ssp, and system_state::ssv.
Referenced by allocation().
phenology()
subroutine phenology_methods::phenology (real(dp) yield, real(dp) laiinc)
Author
Mark Lomas
Date
Feb 2006
Definition at line 51 of file phenology_methods.f90.
References pft_parameters::pft, phenology1(), phenology2(), phenology3(), and site_parameters::ssp.
Referenced by sdgvm().
phenology1()
subroutine phenology_methods::phenology1 (real(dp) yield, real(dp) laiinc)
Author
Mark Lomas
Date
Feb 2006
Definition at line 93 of file phenology_methods.f90.
References misc_values::msv, pft_parameters::pft, site_parameters::ssp, system_state::ssv, and tuning_parameters::tgp.
Referenced by phenology().
phenology2()
subroutine phenology_methods::phenology2 (real(dp) yield, real(dp) laiinc)
Author
Mark Lomas
Date
Feb 2006
Definition at line 345 of file phenology_methods.f90.
References misc_values::msv, pft_parameters::pft, site_parameters::ssp, system_state::ssv, and tuning_parameters::tgp.
Referenced by phenology().
phenology3()
subroutine phenology_methods::phenology3 (real(dp) yield, real(dp) laiinc)
Author
Lyla,EPK
Date
Jan 2017
Definition at line 591 of file phenology_methods.f90.
References light_methods::dayl(), misc_values::msv, pft_parameters::pft, site_parameters::ssp, system_state::ssv, crops::streck(), and crops::wangengel().
Referenced by phenology().
root_add()
subroutine phenology_methods::root_add (real(dp) laiinc, real(dp) leaflit)
Update roots by adding daily increase and removing via mortality.
Root mortality is given in the pft parameters (pftrls).
Author
Mark Lomas
Date
Feb 2006
Definition at line 1264 of file phenology_methods.f90.
References pft_parameters::pft, dims::root_comp_length, site_parameters::ssp, and system_state::ssv.
Referenced by allocation().
root_dist()
subroutine phenology_methods::root_dist (real(dp) respref, real(dp) resp)
Apply root respiration to the active roots, and sum the resulting roots.
Apply root respiration to each of the root compartments which span the age, for the current cohort.
Author
Mark Lomas
Date
Feb 2006
Definition at line 1489 of file phenology_methods.f90.
References site_parameters::ssp, and system_state::ssv.
Referenced by allocation().
stem_add()
subroutine phenology_methods::stem_add (real(dp) stem_inc, real(dp) stem_fixed)
Update stems by adding daily increase and removing via mortality.
Stem mortality is given in the pft parameters (pftsls).
Author
Mark Lomas
Date
Feb 2006
Definition at line 1190 of file phenology_methods.f90.
References pft_parameters::pft, site_parameters::ssp, system_state::ssv, and dims::stem_comp_length.
Referenced by allocation().
stem_dist()
subroutine phenology_methods::stem_dist (real(dp) respref, real(dp) resp)
Apply stem respiration to the active stems, and sum the resulting stems.
Apply stem respiration to each of the stem compartments which span the age, for the current cohort.
Author
Mark Lomas
Date
Feb 2006
Definition at line 1443 of file phenology_methods.f90.
References site_parameters::ssp, and system_state::ssv.
Referenced by allocation().
suma_add()
subroutine phenology_methods::suma_add (real(dp) laiinc)
Update suma by adding daily increase and removing via mortality.
suma mortality is hardwired at 360 days. suma_comp_length set to 30 in dims
Author
Mark Lomas
Date
Feb 2006
Definition at line 1122 of file phenology_methods.f90.
References site_parameters::ssp, system_state::ssv, and dims::suma_comp_length.
Referenced by doly::dolyday().