SDGVM Update Project: state_methods Module Reference
state_methods Module Reference
Functions/Subroutines
subroutine restrict_cohort_numbers ()
subroutine combine_cohorts (co1, co2)
subroutine make_co2ftmap (show)
subroutine remove_cohort (co)
subroutine initialise_state_cohort (cohort)
subroutine sum_carbon (total_carbon, show_all)
subroutine accumulate_dist_soil_res (ft, x)
accumulate_dist_soil_res !
subroutine accumulate_burnt_soil_res (ft, x, firec)
subroutine set_new_soil_res (ft, x)
subroutine set_new_soil_res2 (cohort, ft, x)
subroutine reset_soil_res ()
subroutine initialise_state (nft, cluse, xtmpv, soilt)
Initialise cohorts for the gridcell prior to year loop.
subroutine compress_state ()
Remove cohorts with zero cover.
subroutine ft_cover ()
subroutine set_misc_values (sla, t)
Function/Subroutine Documentation
accumulate_burnt_soil_res()
subroutine state_methods::accumulate_burnt_soil_res (integer ft, real(dp) x, real(dp) firec)
Definition at line 803 of file state_methods.f90.
References pft_parameters::pft, site_parameters::ssp, and system_state::ssv.
Referenced by veg_dynamics::newgrowth().
accumulate_dist_soil_res()
subroutine state_methods::accumulate_dist_soil_res (integer ft, real(dp) x)
accumulate_dist_soil_res !
! Gets called when a cohort needs to die either by fire or ! low NPP.Sends carbon and water pools linked with the specific cohort! to sspnew... to be recycled later.Most importantly it calls ! INITIALISE_STATE_COHORT function which will set ssv parameters for ! this cohort to zero.
Author
Mark Lomas
Date
Feb 2006
Definition at line 674 of file state_methods.f90.
References initialise_state_cohort(), pft_parameters::pft, site_parameters::ssp, and system_state::ssv.
Referenced by veg_dynamics::newgrowth().
combine_cohorts()
subroutine state_methods::combine_cohorts (integer co1, integer co2)
Definition at line 102 of file state_methods.f90.
References dims::lai_comp_length, dims::max_lai_comps, dims::max_par_loops, dims::max_root_comps, dims::max_stem_comps, dims::max_suma_comps, remove_cohort(), dims::root_comp_length, site_parameters::ssp, system_state::ssv, system_state::ssv_temp, dims::stem_comp_length, sum_carbon(), and dims::suma_comp_length.
Referenced by restrict_cohort_numbers().
compress_state()
subroutine state_methods::compress_state ()
Remove cohorts with zero cover.
! Check the cover for each cohort.If it's >0 then it copies ssv and pft structures at a new cohort index thus excluding the ones with cover smaller than zero.For the ones with cover<0 it calls INITIALISE_STATE_COHORT function which sets all values of the ssv elements to zero.
Author
Mark Lomas
Date
Feb 2006
Definition at line 1258 of file state_methods.f90.
References initialise_state_cohort(), make_co2ftmap(), pft_parameters::pft, site_parameters::ssp, and system_state::ssv.
Referenced by veg_dynamics::newgrowth().
ft_cover()
subroutine state_methods::ft_cover ()
Definition at line 1284 of file state_methods.f90.
References dims::max_pfts, pft_parameters::pft, site_parameters::ssp, and system_state::ssv.
initialise_state()
subroutine state_methods::initialise_state (integer nft, real(dp), dimension(max_cohorts,max_years) cluse, real(dp), dimension(500,12,31) xtmpv, real(dp) soilt)
Initialise cohorts for the gridcell prior to year loop.
! Initializes number of cohors and system state for each ft that is present in year 1,checks cluse(ft,1)>0.0. For each ft create as many cohorts as its lifespan in years given by
pftmort.Initial cover for each cohort is given by the ft total
cover of year 1 divided by the number of ft cohorts.It has previously read the pft parameters for each ft from file and assigned them to variable pft_tab(ft).Here is assigns the correct parameters to the same variable type pft(cohort) for each cohort.
Author
Mark Lomas
Date
Feb 2006
Definition at line 1049 of file state_methods.f90.
References file_object::fun, make_co2ftmap(), dims::max_lai_comps, dims::max_pfts, dims::max_root_comps, dims::max_stem_comps, dims::max_suma_comps, pft_parameters::pft, pft_parameters::pft_tab, reset_soil_res(), site_parameters::ssp, and system_state::ssv.
Referenced by sdgvm().
initialise_state_cohort()
subroutine state_methods::initialise_state_cohort (integer cohort)
Definition at line 442 of file state_methods.f90.
References dims::lai_comp_length, dims::max_par_loops, pft_parameters::pft, dims::root_comp_length, system_state::ssv, dims::stem_comp_length, and dims::suma_comp_length.
Referenced by accumulate_dist_soil_res(), compress_state(), and veg_dynamics::initialise_new_cohorts().
make_co2ftmap()
subroutine state_methods::make_co2ftmap (logical show)
Definition at line 368 of file state_methods.f90.
References dims::max_pfts, pft_parameters::pft, pft_parameters::pft_tab, site_parameters::ssp, and system_state::ssv.
Referenced by compress_state(), initialise_state(), remove_cohort(), and restrict_cohort_numbers().
remove_cohort()
subroutine state_methods::remove_cohort (integer co)
Definition at line 408 of file state_methods.f90.
References make_co2ftmap(), pft_parameters::pft, site_parameters::ssp, and system_state::ssv.
Referenced by combine_cohorts().
reset_soil_res()
subroutine state_methods::reset_soil_res ()
Definition at line 974 of file state_methods.f90.
References site_parameters::ssp.
Referenced by veg_dynamics::initialise_new_cohorts(), and initialise_state().
restrict_cohort_numbers()
subroutine state_methods::restrict_cohort_numbers ()
Definition at line 29 of file state_methods.f90.
References combine_cohorts(), make_co2ftmap(), pft_parameters::pft, site_parameters::ssp, and system_state::ssv.
Referenced by sdgvm().
set_misc_values()
subroutine state_methods::set_misc_values (real(dp) sla, real(dp) t)
Structure msv is defined in misc_values
Author
Mark Lomas
Date
Feb 2006
Definition at line 1315 of file state_methods.f90.
References misc_values::msv, site_parameters::ssp, system_state::ssv, and tuning_parameters::tgp.
Referenced by sdgvm().
set_new_soil_res()
subroutine state_methods::set_new_soil_res (integer ft, real(dp) x)
Definition at line 880 of file state_methods.f90.
References site_parameters::ssp, and system_state::ssv.
Referenced by veg_dynamics::initialise_new_cohorts().
set_new_soil_res2()
subroutine state_methods::set_new_soil_res2 (integer cohort, integer ft, real(dp) x)
Definition at line 912 of file state_methods.f90.
References site_parameters::ssp, and system_state::ssv.
sum_carbon()
subroutine state_methods::sum_carbon (real(dp) total_carbon, logical show_all)
Definition at line 548 of file state_methods.f90.
References pft_parameters::pft, site_parameters::ssp, and system_state::ssv.
Referenced by combine_cohorts(), veg_dynamics::cover(), veg_dynamics::growth(), veg_dynamics::initialise_new_cohorts(), soil_methods::soil_dynamics(), and veg_dynamics::thin().