SDGVM Update Project: func Module Reference
func Module Reference
Functions/Subroutines
integer function check_ft_grow (tmp, xchill, xdschill, ft)
integer function minx (x)
integer function no_days (year, mnth, thty_dys)
integer function no_day (year, mnth, day, thty_dys)
subroutine st2arr (st1, x, ix, no)
subroutine stripbn (st1, ans)
subroutine stripbs (st1, st2)
subroutine stripb (st1)
integer function blank (st1)
integer function last_blank (st1)
integer function blanks (st1)
integer function n_fields (st1)
character(str_len) function in2st (int1)
integer function ntags (st1, st2)
integer function stcmp (st1, st2)
subroutine randomv (years, yr0, yrf, idum)
integer function ranv (i, j, idum)
real(dp) function ran1 (idum)
integer function round (x)
subroutine matcheck (x, a, b, c, d, check, ind, n)
subroutine pile4 (x, a, b, c, d, n)
subroutine pile1 (x, a, n)
Function/Subroutine Documentation
blank()
integer function func::blank (character(len=str_len) st1)
Definition at line 358 of file func.f90.
References dims::str_len.
Referenced by data::ex_clu(), crops::read_fertilizers(), crops::read_irrigation(), read_input::read_param(), sdgvm1::set_pixel_out(), sdgvm1::set_subpixel_out(), stripbn(), and stripbs().
blanks()
integer function func::blanks (character(len=str_len) st1)
Definition at line 414 of file func.f90.
References dims::str_len.
Referenced by n_fields(), stripb(), stripbn(), and stripbs().
check_ft_grow()
integer function func::check_ft_grow (real(dp), dimension(12,31) tmp, integer xchill, integer xdschill, integer ft)
Definition at line 20 of file func.f90.
References pft_parameters::pft, and pft_parameters::pft_tab.
Referenced by sdgvm1::set_landuse().
in2st()
character(str_len) function func::in2st (integer int1)
Definition at line 475 of file func.f90.
References dims::str_len.
Referenced by data::ex_clu(), open_files::open_snapshots(), crops::read_fertilizers(), and crops::read_irrigation().
last_blank()
integer function func::last_blank (character(len=str_len) st1)
Definition at line 386 of file func.f90.
References dims::str_len.
matcheck()
subroutine func::matcheck (real(dp), dimension(n,4) x, real(dp) a, real(dp) b, real(dp) c, real(dp) d, real(dp) check, integer ind, integer n)
Definition at line 710 of file func.f90.
minx()
integer function func::minx (real(dp), dimension(12) x)
Definition at line 97 of file func.f90.
Referenced by veg_dynamics::fire().
n_fields()
integer function func::n_fields (character(len=str_len) st1)
Definition at line 444 of file func.f90.
References blanks(), dims::str_len, and stripbs().
Referenced by data::ex_clu(), data::ex_lu(), crops::read_fertilizers(), crops::read_irrigation(), sdgvm1::set_pixel_out(), and sdgvm1::set_subpixel_out().
no_day()
integer function func::no_day (integer year, integer mnth, integer day, integer thty_dys)
Definition at line 166 of file func.f90.
References no_days().
Referenced by productivity_methods::nppcalc().
no_days()
integer function func::no_days (integer year, integer mnth, integer thty_dys)
Definition at line 127 of file func.f90.
Referenced by data::ex_clim_site(), no_day(), crops::seasonality(), and sdgvm1::set_climate().
ntags()
integer function func::ntags (character(len=str_len), dimension(max_outputs) st1, character(len=str_len) st2)
Definition at line 506 of file func.f90.
References dims::max_pfts, and stcmp().
Referenced by sdgvm1::read_landuse(), sdgvm1::set_pixel_out(), and sdgvm1::set_subpixel_out().
pile1()
subroutine func::pile1 (real(dp), dimension(n) x, real(dp) a, integer n)
Definition at line 775 of file func.f90.
pile4()
subroutine func::pile4 (real(dp), dimension(n,4) x, real(dp) a, real(dp) b, real(dp) c, real(dp) d, integer n)
Definition at line 742 of file func.f90.
ran1()
real(dp) function func::ran1 (integer idum)
Definition at line 627 of file func.f90.
Referenced by ranv().
randomv()
subroutine func::randomv (integer, dimension(yrf-yr0+1) years, integer yr0, integer yrf, integer idum)
Definition at line 576 of file func.f90.
References ranv().
Referenced by read_input::process_input_file().
ranv()
integer function func::ranv (integer i, integer j, integer idum)
Definition at line 607 of file func.f90.
References ran1().
Referenced by randomv().
round()
integer function func::round (real(dp) x)
Definition at line 671 of file func.f90.
st2arr()
subroutine func::st2arr (character(len=str_len) st1, integer, dimension(max_years) x, integer ix, integer no)
Definition at line 195 of file func.f90.
References stripbn().
Referenced by data::ex_clu(), data::ex_lu(), crops::read_fertilizers(), and crops::read_irrigation().
stcmp()
integer function func::stcmp (character(len=str_len) st1, character(len=str_len) st2)
Definition at line 540 of file func.f90.
Referenced by data::ex_clu(), ntags(), read_input::process_input_file(), crops::read_fertilizers(), crops::read_irrigation(), read_input::read_param(), sdgvm1::set_pixel_out(), and sdgvm1::set_subpixel_out().
stripb()
subroutine func::stripb (character(len=str_len) st1)
Definition at line 325 of file func.f90.
References blanks(), and dims::str_len.
Referenced by data::ex_clu(), open_files::open_snapshots(), crops::read_fertilizers(), crops::read_irrigation(), read_input::read_param(), sdgvm1::set_pixel_out(), and sdgvm1::set_subpixel_out().
stripbn()
subroutine func::stripbn (character(len=str_len) st1, integer ans)
Definition at line 227 of file func.f90.
References blank(), blanks(), and dims::str_len.
Referenced by sdgvm1::set_pixel_out(), sdgvm1::set_subpixel_out(), and st2arr().
stripbs()
subroutine func::stripbs (character(len=str_len) st1, character(len=str_len) st2)
Definition at line 279 of file func.f90.
References blank(), blanks(), and dims::str_len.
Referenced by n_fields(), read_input::process_input_file(), read_input::read_param(), sdgvm1::set_pixel_out(), and sdgvm1::set_subpixel_out().