SDGVM Update Project: C:/Users/markl/Dropbox/SDGVM/source/f03_ant/src/sdgvm.f90 File Reference
sdgvm.f90 File Reference
Functions/Subroutines
program sdgvm
Function/Subroutine Documentation
sdgvm()
program sdgvm ()
Definition at line 9 of file sdgvm.f90.
References phenology_methods::allocation(), sdgvm1::co2_0_f(), sdgvm1::country(), light_methods::dayl(), doly::dolyday(), real_precision::dp, doly::evapotranspiration(), crops::fert_crops(), fnames_object::fnms, file_object::fun, sdgvm1::get_input_filename(), hydrology_methods::hydrology(), state_methods::initialise_state(), crops::irrigate(), dims::max_cohorts, dims::max_outputs, dims::max_years, sdgvm1::mkdlit(), sdgvm1::outputs(), light_methods::pfd_ant(), pft_parameters::pft, pft_parameters::pft_tab, phenology_methods::phenology(), file_class::print(), read_input::process_input_file(), sdgvm1::read_climate(), crops::read_fertilizers(), crops::read_irrigation(), sdgvm1::read_landuse(), read_input::read_param(), sdgvm1::read_soil(), state_methods::restrict_cohort_numbers(), crops::seasonality(), sdgvm1::set_climate(), sdgvm1::set_co2(), sdgvm1::set_landuse(), state_methods::set_misc_values(), soil_methods::soil_dynamics2(), system_state::ssv, dims::str_len, sdgvm1::sum_soilcn(), and soil_methods::wsparam().